-- The words as they stood when they moved in.
--
-- A one-time load, not a source: from here the database is where content is
-- written and this file is only how an empty one is filled. It is the reason
-- a fresh environment — a new developer, production on its first day — comes
-- up with something to say.


INSERT INTO archetypes (id, locale, name, summary, motto, ordinal) VALUES
  ('quiet_builder', 'tr', 'Sessiz İnşacı', 'Gürültü çıkarmadan biriktirirsin; kimse ilk taşı görmez, herkes duvarı görür. Bedeli şu: görünmediğin için çoğu zaman hakkın da teslim edilmez.', 'Acele etmeyen ama durmayan.', 1),
  ('spark', 'tr', 'Kıvılcım', 'Bir sürü şeye başlarsın ve sorun ilgisizlik değil — hepsinin gerçekten iyi fikir olması. Zor olan tutuşturmak değil, birini seçmek.', 'Bugün sadece bir tanesi.', 2),
  ('night_watch', 'tr', 'Gece Nöbetçisi', 'Sen fark ettiğinde iş henüz olmamıştır. Herkes rahatken senin çoktan düşünmüş olman yorucu, ama defalarca işe yaradı.', 'Tetikte olmak da bir güç, dinlenmek de.', 3),
  ('table_setter', 'tr', 'Sofra Kuran', 'İnsanları bir araya getiren sensin ve bunu kimse senden istemiyor bile. Herkesin iyi hissetmesini o kadar önemsiyorsun ki, sıra sana geldiğinde masada yer kalmıyor.', 'Onlardan önce bir de bana sor.', 4),
  ('fine_worker', 'tr', 'İnce İşçi', '"Olur böyle" cümlesi sende çalışmıyor; farkı kimsenin görmediği yerde de görüyorsun. Bitirmeni zorlaştıran şey tembellik değil, standardın.', 'Mükemmel değil, bitmiş olsun.', 5),
  ('compass', 'tr', 'Yön Veren', 'Kimse karar vermeyince sen veriyorsun ve genelde doğru çıkıyor. Bedeli: herkesin katılmasını beklemediğin için bazen yalnız yürüyorsun.', 'Karar vermek de bir yük, taşıyorum.', 6),
  ('still_water', 'tr', 'Durgun Su', 'Herkes telaşlanırken sen sakin kalıyorsun ve bu, etrafındakileri de sakinleştiriyor. Ama o kadar sorun etmiyorsun ki, gerçekten sorun olan şey de gecikiyor.', 'Sakinim, kayıtsız değil.', 7),
  ('deep_diver', 'tr', 'Derin Dalgıç', 'Her şeyi bir kat daha derinden yaşıyorsun; iyisini de kötüsünü de. Yüzeyde kalabilseydin rahat ederdin ama o zaman sen olmazdın.', 'Derinde kalmak değil, dalıp çıkmak.', 8),
  ('own_clock', 'tr', 'Kendi Saatinde', 'Sistemle değil, dalgayla çalışıyorsun; geldiğinde tamamen geliyor. Bedeli şu: hiçbir şey birikmiyor, ve kimse sana göre plan yapamıyor — sen de dahil.', 'Kendi saatimde ama her gün.', 9),
  ('contrarian', 'tr', 'Aykırı', 'Ne düzenmiş gibi yapıyorsun ne de katılıyormuş gibi, o yüzden senden duyduğun şey gerçek olan. Bedeli şu: sonradan ihtiyacın olacak iyi niyeti bugün harcıyorsun.', 'Karşı çıkmak kolay, sürdürmek zor.', 10),
  ('feet_on_ground', 'tr', 'Ayağı Yerde', 'Bugünün işine bakıyorsun ve elindekiyle çözüyorsun; teoriye de plana da ihtiyacın olmuyor. Bedeli şu: hiçbir şey değişmiyor, çünkü değişim ya merak ister ya plan, ikisini de taşımıyorsun.', 'Bugün elimde olanla.', 11),
  ('as_is', 'tr', 'Olduğu Gibi', 'Ne yakınlık için uğraşıyorsun ne de araları düzeltmek için; seni tanıyan, tam olarak seni tanıyor. Bedeli şu: bir süre sonra kimse sormuyor, ve bunu ancak bir şeye ihtiyacın olduğunda fark ediyorsun.', 'Az kişiye açık, onlara tamamen.', 12),
  ('table_upsetter', 'tr', 'Masayı Deviren', 'Odada kimsenin söylemediği şeyi sen söylüyorsun ve genelde söylenmesi gerekiyordu. Bedeli şu: söyledikten sonra orada kalman gerekiyor, ve kalmak söylemekten çok daha zor.', 'Söylemesi kolaydı, kalması değil.', 13),
  ('light_footed', 'tr', 'Hafif Ayaklı', 'Kalabalık da aksilik de seni yormuyor; ikisinin içinden aynı rahatlıkla geçiyorsun. Bedeli şu: hiçbir şeyi büyütmediğin için gerçekten büyük olanı da geç fark ediyorsun.', 'Taşımadan da gidilir, ama bunu değil.', 14),
  ('full_glass', 'tr', 'Dolu Bardak', 'Her şeyi aynı anda ve tamamen hissediyorsun, o yüzden zor olan ne yapacağın değil neyi önce yapacağın. Bedeli şu: taşmamak için harcadığın enerjiyi işin kendisine ayıramıyorsun.', 'Bir yudum boşalt, sonra taşı.', 15),
  ('word_is_bond', 'tr', 'Sözü Senet', 'Söylediğin şey oluyor ve insanlar bunu sen söylemeden önce biliyorlar. Bedeli şu: kimse senden "yapamam" duymadığı için sormaya da devam ediyor, ve sıra kendi işine en son geliyor.', 'Söz verdiğim kadarı, o kadarı da tam.', 16),
  ('in_its_place', 'tr', 'Yerli Yerinde', 'Denenmiş olanı denenmiş olduğu için seçiyorsun ve bu seni sarsılmaz yapıyor; etrafındakiler de bunu bilerek plan yapıyor. Bedeli şu: değişmesi gereken şey de aynı yerde duruyor, çünkü onu da yerinde sanıyorsun.', 'Yerinde duranı da bir yokla.', 17),
  ('inwardly', 'tr', 'İçten İçe', 'Kimseye söylemeden çok şey taşıyorsun; birinin canı sıkkınsa sen zaten fark etmişsindir. Bedeli şu: fark ettiğini söylemediğin için yardım hep tek yönlü akıyor, ve bir gün sana lazım olduğunda kimsenin aklına gelmiyorsun.', 'Ben de söyleyebilirim.', 18);


INSERT INTO archetype_rules (archetype_id, defining, openness, conscientiousness, extraversion, agreeableness, neuroticism) VALUES
  ('quiet_builder', ARRAY['conscientiousness','extraversion'], 0.5, 0.85, 0.15, 0.5, 0.5),
  ('spark', ARRAY['openness','extraversion','conscientiousness'], 0.85, 0.2, 0.8, 0.6, 0.5),
  ('night_watch', ARRAY['conscientiousness','neuroticism'], 0.5, 0.8, 0.4, 0.5, 0.8),
  ('table_setter', ARRAY['agreeableness','extraversion'], 0.5, 0.5, 0.8, 0.85, 0.45),
  ('fine_worker', ARRAY['openness','conscientiousness'], 0.8, 0.85, 0.4, 0.5, 0.5),
  ('compass', ARRAY['extraversion','conscientiousness','agreeableness'], 0.5, 0.8, 0.8, 0.2, 0.35),
  ('still_water', ARRAY['neuroticism','agreeableness','extraversion'], 0.45, 0.5, 0.25, 0.75, 0.15),
  ('deep_diver', ARRAY['openness','neuroticism','extraversion'], 0.85, 0.45, 0.2, 0.55, 0.75),
  ('own_clock', ARRAY['conscientiousness','extraversion'], 0.45, 0.1, 0.2, 0.6, 0.5),
  ('contrarian', ARRAY['conscientiousness','agreeableness'], 0.6, 0.15, 0.6, 0.1, 0.5),
  ('feet_on_ground', ARRAY['openness','conscientiousness'], 0.1, 0.3, 0.5, 0.65, 0.45),
  ('as_is', ARRAY['extraversion','agreeableness'], 0.45, 0.6, 0.15, 0.15, 0.5),
  ('table_upsetter', ARRAY['extraversion','agreeableness','neuroticism'], 0.55, 0.45, 0.78, 0.15, 0.68),
  ('light_footed', ARRAY['extraversion','neuroticism'], 0.5, 0.48, 0.82, 0.55, 0.08),
  ('full_glass', ARRAY['conscientiousness','neuroticism'], 0.55, 0.18, 0.5, 0.5, 0.9),
  ('word_is_bond', ARRAY['agreeableness','conscientiousness'], 0.45, 0.82, 0.5, 0.85, 0.5),
  ('in_its_place', ARRAY['openness','conscientiousness','neuroticism'], 0.15, 0.78, 0.5, 0.55, 0.25),
  ('inwardly', ARRAY['agreeableness','extraversion','neuroticism'], 0.5, 0.5, 0.2, 0.8, 0.72);


INSERT INTO item_sets (version, active) VALUES (1, true);


INSERT INTO items (id, version, locale, dimension, reverse, text, ordinal) VALUES
  ('e1', 1, 'tr', 'extraversion', false, 'Kalabalık ortamlarda kendimi rahat hissederim.', 1),
  ('e2', 1, 'tr', 'extraversion', false, 'Tanımadığım insanlarla konuşmaya ilk ben başlarım.', 2),
  ('e3', 1, 'tr', 'extraversion', true, 'Uzun süre yalnız kalmak beni dinlendirir.', 3),
  ('e4', 1, 'tr', 'extraversion', true, 'Bir gruptayken çoğunlukla dinlemeyi tercih ederim.', 4),
  ('a1', 1, 'tr', 'agreeableness', false, 'Başkalarının nasıl hissettiğini kolayca fark ederim.', 5),
  ('a2', 1, 'tr', 'agreeableness', false, 'Birinin işi zorlaşınca yardım etmek içimden gelir.', 6),
  ('a3', 1, 'tr', 'agreeableness', true, 'Haklı olduğuma inanıyorsam tartışmayı sürdürürüm.', 7),
  ('a4', 1, 'tr', 'agreeableness', true, 'İnsanların çoğu, gerekirse kendi çıkarını gözetir diye düşünürüm.', 8),
  ('c1', 1, 'tr', 'conscientiousness', false, 'Başladığım işi bitirmeden rahat edemem.', 9),
  ('c2', 1, 'tr', 'conscientiousness', false, 'Bir işe başlamadan önce nasıl yapacağımı planlarım.', 10),
  ('c3', 1, 'tr', 'conscientiousness', true, 'İşleri son ana bırakırım.', 11),
  ('c4', 1, 'tr', 'conscientiousness', true, 'Eşyalarımın yerini sık sık kaybederim.', 12),
  ('n1', 1, 'tr', 'neuroticism', false, 'Küçük aksilikler bile canımı sıkabiliyor.', 13),
  ('n2', 1, 'tr', 'neuroticism', false, 'Olabilecek kötü şeyleri önceden düşünürüm.', 14),
  ('n3', 1, 'tr', 'neuroticism', true, 'Baskı altında sakin kalırım.', 15),
  ('n4', 1, 'tr', 'neuroticism', true, 'Bir şey ters gittiğinde çabuk toparlanırım.', 16),
  ('o1', 1, 'tr', 'openness', false, 'Yeni fikirler beni kolayca meraklandırır.', 17),
  ('o2', 1, 'tr', 'openness', false, 'Alışılmadık, denenmemiş çözümler ilgimi çeker.', 18),
  ('o3', 1, 'tr', 'openness', true, 'Bildiğim yöntemi değiştirmek için iyi bir sebep isterim.', 19),
  ('o4', 1, 'tr', 'openness', true, 'Hayal kurmaktansa elimdeki işe odaklanırım.', 20);


INSERT INTO mottos (id, locale, archetype_id, motto, detail, reminder, ordinal) VALUES
  ('qb1', 'tr', 'quiet_builder', 'Acele etmeyen ama durmayan.', 'Hızlanmak sana bir şey kazandırmıyor, durmak her şeyi kaybettiriyor. Bedeli, ilerlediğini uzun süre kimsenin — bazen senin bile — fark etmemesi.', 'Bugün de bir taş.', 1),
  ('qb2', 'tr', 'quiet_builder', 'İlk taşı ben biliyorum.', 'Duvarı herkes görür, nereden başladığını sen bilirsin. Bunu bilmek yeterli olmalı; çoğu zaman olmuyor ve bu yorucu.', 'Nereden başladığını hatırla.', 2),
  ('qb3', 'tr', 'quiet_builder', 'Gösterebileceğim kadarı yeter.', 'Bitmemiş bir şeyi göstermek sana yanlış geliyor. Ama hiç göstermezsen hakkın da teslim edilmiyor — bu ikisi arasında bir yer var.', 'Bugünlük bu kadarı görünsün.', 3),
  ('qb4', 'tr', 'quiet_builder', 'Sessizlik yavaşlık değil.', 'Ses çıkarmadan çalışmak, az çalışmak sanılıyor. Doğrusunu bilmek senin işine yarar; başkasına anlatmak da bazen gerekiyor.', 'Sessiz ama duruyor.', 4),
  ('sp1', 'tr', 'spark', 'Bugün sadece bir tanesi.', 'Fikirlerin kötü değil, fazla. Seçmek eleme değil vazgeçme olduğu için zor — ve vazgeçmediğin sürece hiçbiri ilerlemiyor.', 'Bir tanesi. Sadece bugün.', 1),
  ('sp2', 'tr', 'spark', 'Tutuşturmak kolay, taşımak marifet.', 'Başlangıçta iyisin ve bunu biliyorsun. Asıl mesele heyecan bittikten sonra kalan kısım, ki orası sıkıcı olduğu için yürüyor.', 'Heyecan bitti, iş duruyor.', 2),
  ('sp3', 'tr', 'spark', 'Yaz ve bırak.', 'Yeni fikir gelmesini engelleyemezsin, peşinden gitmeyi erteleyebilirsin. Bir yere yazılan fikir kaçmıyor; kovalanan fikir bugünü yiyor.', 'Yazdın mı? Yeter.', 3),
  ('sp4', 'tr', 'spark', 'Kaçıncı gün, kaç fikir değil.', 'Sende ölçü hep üretilen sayıydı. Bu sefer ölçü aynı şeye kaçıncı kez döndüğün — daha az heyecanlı ama daha çok işe yarıyor.', 'Aynı şeye bir kez daha dön.', 4),
  ('nw1', 'tr', 'night_watch', 'Tetikte olmak da bir güç, dinlenmek de.', 'Önceden görmen defalarca işe yaradı, o yüzden bırakmıyorsun. Ama nöbet her gün tutulmuyor ve bunu kimse sana söylemiyor.', 'Bugün nöbet yok.', 1),
  ('nw2', 'tr', 'night_watch', 'Listenin tamamı bugünün işi değil.', 'Ters gidebilecek her şeyi zaten düşündün. Hepsini bugün çözmeye çalışmak, hiçbirini çözmemekle aynı yere çıkıyor.', 'Bir madde. Bugünlük o kadar.', 2),
  ('nw3', 'tr', 'night_watch', 'Bir gün affedilir.', 'Kaçırdığın gün değil, kaçırdıktan sonra kurduğun senaryo yoruyor. Zincir bir günü affediyor — sen genelde affetmiyorsun.', 'Bir gün bir şey değiştirmez.', 3),
  ('nw4', 'tr', 'night_watch', 'Hazırlık da bir iş, o da bitiyor.', 'Hazırlanmak sende hiç bitmiyor çünkü her zaman bir ihtimal daha var. Bir yerde durmak, hazırlıksız kalmak değil.', 'Yeterince hazırsın.', 4),
  ('ts1', 'tr', 'table_setter', 'Onlardan önce bir de bana sor.', 'Herkesin iyi hissetmesini ayarlarken sıra sana gelmiyor. Bu bir fedakârlık değil, alışkanlık — ve alışkanlıklar değişebiliyor.', 'Bugünkü dakika senin.', 1),
  ('ts2', 'tr', 'table_setter', 'Kendime verdiğim söz de sözdür.', 'Başkasına verdiğin sözü tutuyorsun. Kendine verdiğini bozarken kimseden özür dilemediğin için bedava geliyor; gelmiyor.', 'Söz vermiştin.', 2),
  ('ts3', 'tr', 'table_setter', 'Masayı kuran da oturur.', 'İnsanları bir araya getirmek senin işin oldu. Sofrada kendine yer ayırmak, o işi bırakmak anlamına gelmiyor.', 'Otur.', 3),
  ('ts4', 'tr', 'table_setter', 'Bunu kimseye anlatmak zorunda değilim.', 'Yaptığın çoğu şeyin bir izleyicisi var. Bunun yok, ve olmaması onu değersiz yapmıyor — sadece sessiz yapıyor.', 'Kimse görmese de olur.', 4),
  ('fw1', 'tr', 'fine_worker', 'Mükemmel değil, bitmiş olsun.', 'Yarım kalanların çoğu tembellikten değil standardından yarım kaldı. Standart iyi bir şey; her yerde aynı standardı uygulamak değil.', 'Bitmiş olsun, yeter.', 1),
  ('fw2', 'tr', 'fine_worker', 'Şimdilik böyle.', '"Böyle olmaz" cümlesi işi durduruyor, "şimdilik böyle" ilerletiyor. İkisi de geçici, biri ilerleme bırakıyor.', 'Şimdilik yeter.', 2),
  ('fw3', 'tr', 'fine_worker', 'Farkı ben görüyorum, bugün görmeyeyim.', 'Kimsenin görmediği farkı görmek bir yetenek ve bir yük. Bugünlük yükü bırakmak, yeteneği kaybetmek değil.', 'Bugün bakma.', 3),
  ('fw4', 'tr', 'fine_worker', 'Bir kademe aşağısı da iş görür.', 'En iyisini yapmak zaman alıyor ve o zaman başka bir şeyden çalınıyor. Neyin en iyi olması gerektiğini seçmek de bir ustalık.', 'Bir kademe aşağı.', 4),
  ('cp1', 'tr', 'compass', 'Karar vermek de bir yük, taşıyorum.', 'Kimse karar vermeyince sen veriyorsun ve genelde doğru çıkıyor. Bedeli, taşıdığın şeyin ağırlığını kimsenin görmemesi — küçük kararlar dahil.', 'Bugünkü karar küçük. Yine de sende.', 1),
  ('cp2', 'tr', 'compass', 'Bu sefer kimseyi ikna etmeyeceğim.', 'Herkesi beklemeden yürüyorsun ve genelde haklı çıkıyorsun. Bugünkü işin kimseyi ilgilendirmiyor; ikna edilecek tek kişi sensin.', 'Sadece seni ilgilendiriyor.', 2),
  ('cp3', 'tr', 'compass', 'Bırak ilerlesin.', 'Yavaş gideni hızlandırma refleksin var. Bazı şeyler müdahaleyle değil, zamanla ilerliyor — ve beklemek sende en zor kısım.', 'Bugün karışma.', 3),
  ('cp4', 'tr', 'compass', 'Yön göstermek de yoruyor.', 'Kimse senden istemedi ama sen yapıyorsun. Yorulmanın sebebi iş değil, işin kime ait olduğunun hiç konuşulmaması.', 'Bugünkü yön seninki.', 4),
  ('sw1', 'tr', 'still_water', 'Sakinim, kayıtsız değil.', 'Telaşa kapılmaman umursamamak sanılıyor. Aynı sakinlik ertelemeyi de rahatsız edici olmaktan çıkarıyor — asıl dikkat etmen gereken yer orası.', 'Sakin ol ama bugün yap.', 1),
  ('sw2', 'tr', 'still_water', 'Sakinliğin bir bedeli var.', 'Çevrendekiler senin sakinliğinden faydalanıyor. Bunun sana neye mal olduğunu genelde sadece sen biliyorsun ve söylemiyorsun.', 'Bugün kendine de bak.', 2),
  ('sw3', 'tr', 'still_water', 'Kendimi biraz rahatsız edeyim.', 'Kimseyi rahatsız etmeden yaşamayı beceriyorsun. Değişim tam olarak rahatsızlığın olduğu yerde oluyor.', 'Küçük bir rahatsızlık.', 3),
  ('sw4', 'tr', 'still_water', 'Durgun, ama duruyor.', 'Dışarıdan hareketsiz görünmek durmakla karıştırılıyor. Aradaki farkı bilen tek kişi sensin; bugün onu doğru tarafta tut.', 'Duruyorsun.', 4),
  ('dd1', 'tr', 'deep_diver', 'Derinde kalmak değil, dalıp çıkmak.', 'Bir konuya girdiğinde dibine gidiyorsun; orada kalmak da kolay. Değerli olan derinlik değil, geri çıkıp bir şey getirebilmen.', 'Dal, sonra çık.', 1),
  ('dd2', 'tr', 'deep_diver', 'Anlamadan da yapılır.', 'Anlamadığın bir şeyi yapmak sana ters geliyor. Ama bazı şeyler yapıldıkça anlaşılıyor, öncesinde değil.', 'Anlamı sonra gelecek.', 2),
  ('dd3', 'tr', 'deep_diver', 'Hazır olacağım gün yok.', 'Hazır hissettiğinde başlamayı seviyorsun. O his gelmiyor; gelenler başlamış olanlar.', 'Bugün başla.', 3),
  ('dd4', 'tr', 'deep_diver', 'Yüzeyde de bir şeyler oluyor.', 'Derinde olan biteni görüyorsun, yüzeydekini kaçırıyorsun. Kaçırdığın şeylerin çoğu orada duruyor.', 'Bir dakika yukarı çık.', 4),
  ('oc1', 'tr', 'own_clock', 'Kendi saatimde ama her gün.', 'Saatini değiştirmene gerek yok, her gün olmasına var. Bedeli, ilhamın gelmediği günlerde de küçük bir şey yapmayı kabul etmek.', 'Bugün de kendi saatinde.', 1),
  ('oc2', 'tr', 'own_clock', 'Dalga geçtiğinde de kıyıdayım.', 'İyi günde çok, kötü günde az — ama ikisinde de var. Bedeli, az olan günü bir başarısızlık saymamayı öğrenmek.', 'Az da olsa bugün de.', 2),
  ('oc3', 'tr', 'own_clock', 'Sistem değil, bugün.', 'Sana kurulacak düzen yaramıyor; yarayan tek şey bugünün kendisi. Bedeli, yarını kimsenin — senin de — kestirememesi.', 'Sadece bugün. Yeter.', 3),
  ('oc4', 'tr', 'own_clock', 'Biriktirmeyi yeni öğreniyorum.', 'Şimdiye kadar biriken bir şey olmadı ve bu bir kusur değil, bir alışkanlık boşluğu. Bedeli, ilk iki haftanın sıkıcı geçmesi.', 'Bir gün daha ekle.', 4),
  ('ct1', 'tr', 'contrarian', 'Karşı çıkmak kolay, sürdürmek zor.', 'İtiraz etmek sana bedavaya geliyor; asıl mesele itiraz ettiğin şeyin yerine bir şey koyup onu sürdürmek. Bedeli, haklı olmanın yetmediğini kabul etmek.', 'Bugün sürdür.', 1),
  ('ct2', 'tr', 'contrarian', 'Kimseye değil, kendime söz verdim.', 'Başkasının kurduğu düzen sende tutmuyor, kendi kurduğun tutabilir. Bedeli, tutmadığında suçlayacak kimsenin olmaması.', 'Sözün sana.', 2),
  ('ct3', 'tr', 'contrarian', 'Uymuyorum, kaçmıyorum.', 'Katılmamak bir duruş, ortadan kaybolmak değil. Bedeli, kalıp tartışmanın kaçmaktan daha yorucu olması.', 'Bugün kal ve yap.', 3),
  ('ct4', 'tr', 'contrarian', 'Ham hâlim, işlenmiş hâlimden dürüst.', 'Cilalamadığın için insanlar seninle nerede olduklarını biliyor. Bedeli, cilanın bazen kapı açtığı yerlerde kapının kapalı kalması.', 'Olduğun gibi, ama bugün yap.', 4),
  ('fg1', 'tr', 'feet_on_ground', 'Bugün elimde olanla.', 'Hazırlık beklemiyorsun, elindekiyle başlıyorsun ve bu çoğu insanın yapamadığı şey. Bedeli, elindeki hep aynı kaldığı için sonucun da aynı kalması.', 'Elindekiyle başla.', 1),
  ('fg2', 'tr', 'feet_on_ground', 'Küçük bir şeyi değiştirmek de değişimdir.', 'Büyük planlar sende çalışmıyor; tek bir ayrıntı çalışıyor. Bedeli, tek ayrıntının sonucu göstermesinin haftalar sürmesi.', 'Bir şeyi değiştir.', 2),
  ('fg3', 'tr', 'feet_on_ground', 'Yaparak öğrenirim, okuyarak değil.', 'Anlatılan şey sende tutmuyor, yapılan tutuyor. Bedeli, aynı hatayı bir kere yapmadan öğrenememek.', 'Bugün yaparak öğren.', 3),
  ('fg4', 'tr', 'feet_on_ground', 'Merak etmesem de deneyebilirim.', 'Yeni olan seni çekmiyor ve çekmesine gerek de yok — denemek merak gerektirmiyor. Bedeli, ilk denemenin garip hissettirmesi.', 'Merak etmeden dene.', 4),
  ('ai1', 'tr', 'as_is', 'Az kişiye açık, onlara tamamen.', 'Herkese biraz olmaktansa birkaç kişiye tamamen olmayı seçiyorsun. Bedeli, o birkaç kişi meşgulken kimsenin kalmaması.', 'Bugün bir kişiye yaz.', 1),
  ('ai2', 'tr', 'as_is', 'Evetim evet, hayırım hayır.', 'Kimseyi idare etmediğin için sözün karşılığı var. Bedeli, idare edilmeyi bekleyen insanların bir daha gelmemesi.', 'Bugünkü sözün sana.', 2),
  ('ai3', 'tr', 'as_is', 'Yalnızlık değil, seçicilik.', 'Uzak durman bir eksiklik değil, bir tercih — ama tercih olduğunu ara ara kontrol etmek gerekiyor. Bedeli, kontrol etmeyi unuttuğunda tercihin alışkanlığa dönüşmesi.', 'Bugün bir kere kontrol et.', 3),
  ('ai4', 'tr', 'as_is', 'Kendim için yapıyorum, kimse görmese de.', 'Motivasyonun dışarıdan gelmiyor, bu yüzden dışarıdan da bozulmuyor. Bedeli, tıkandığında kimsenin fark etmemesi.', 'Kendin için, bugün de.', 4),
  ('tu1', 'tr', 'table_upsetter', 'Söylemesi kolaydı, kalması değil.', 'Doğru cümleyi kurmak sende bir cesaret işi değil, bir refleks. Asıl iş ondan sonra başlıyor ve bedeli şu: söyleyip çıkarsan haklı olman da kimsenin işine yaramıyor.', 'Bugün söylediğinin yanında kal.', 1),
  ('tu2', 'tr', 'table_upsetter', 'Masayı devirdiysem toplarım.', 'Kırdığın şeyi sen de görüyorsun, sadece kırmaya değer olduğunu düşünüyorsun. İkisi birden doğru olabilir; toplamayı da işin parçası say.', 'Bugün bir tanesini topla.', 2),
  ('tu3', 'tr', 'table_upsetter', 'Sesimi değil, sırayı ayarlıyorum.', 'Söylediğin şeyin yanlış olduğu nadir; zamanlaması genelde. Aynı cümle beş dakika sonra kurulduğunda kimse savunmaya geçmiyor.', 'Aynı şeyi, beş dakika sonra.', 3),
  ('tu4', 'tr', 'table_upsetter', 'Katılmıyorum, ama buradayım.', 'Karşı çıkmak seni odadan çıkarmak zorunda değil. Bunu söylemek zor geliyor çünkü kalmak, itiraz etmekten daha çok şey istiyor senden.', 'Katılma, ama kalmaya devam et.', 4),
  ('lf1', 'tr', 'light_footed', 'Taşımadan da gidilir, ama bunu değil.', 'Yükü bırakabilmek senin en rahat özelliğin. Bedeli şu: bırakılmaması gereken şeyi de aynı kolaylıkla bırakıyorsun ve bunu aylar sonra fark ediyorsun.', 'Bugün bırakmayacağın şeyi seç.', 1),
  ('lf2', 'tr', 'light_footed', 'Sakinliğim bir cevap değil.', 'Telaşlanmaman etrafındakileri rahatlatıyor. Ama bazen insanların ihtiyacı rahatlamak değil, ciddiye alındığını görmek.', 'Bugün birine "ciddi bu" de.', 2),
  ('lf3', 'tr', 'light_footed', 'Kolay geldi diye küçük değil.', 'Zorlanmadan yaptığın şeyi kendi gözünde küçültüyorsun. Bir şeyin değeri, sana kaça mal olduğuyla ölçülmüyor.', 'Kolay yaptığın şeyi de say.', 3),
  ('lf4', 'tr', 'light_footed', 'Bugün de aynı yerden geçeyim.', 'Her yerden rahat geçtiğin için hiçbir yerde iz bırakmıyorsun. Aynı yere ikinci kez uğramak, senin için tekrar değil birikim.', 'Dün nereye uğradıysan, bugün de.', 4),
  ('fu1', 'tr', 'full_glass', 'Bir yudum boşalt, sonra taşı.', 'Elindeki her şey aynı anda acil görünüyor ve bu bir dikkat sorunu değil, bir doluluk sorunu. Bedeli şu: boşaltmadığın sürece hiçbirine sıra gelmiyor.', 'Bugün bir tanesini bırak.', 1),
  ('fu2', 'tr', 'full_glass', 'Hissetmem, yapamayacağım demek değil.', 'Bir şeyi yoğun hissetmek sende çoğu zaman erteleme olarak çıkıyor. Aradaki bağ zorunlu değil; hissederken de yapılabiliyor.', 'Şu an nasılsan öyle başla.', 2),
  ('fu3', 'tr', 'full_glass', 'Küçük olsun, bitmiş olsun.', 'Büyük planlar seni rahatlatıyor ve sonra aynı planlar üzerine yıkılıyor. Bitmiş küçük bir şey, planlanmış büyük bir şeyden daha çok taşıyor seni.', 'Beş dakikalık olanı seç.', 3),
  ('fu4', 'tr', 'full_glass', 'Bugünü kurtarmak yeterli.', 'İleriyi düşünmek sende hazırlık değil, yorgunluk üretiyor. Bugünle sınırlı kalmak bir küçülme değil; taşımayı sürdürebilmenin yolu.', 'Sadece bugün. Yarını yarın.', 4),
  ('wb1', 'tr', 'word_is_bond', 'Söz verdiğim kadarı, o kadarı da tam.', 'Verdiğin sözün tutulacağını herkes biliyor. Bedeli şu: ne kadar söz verdiğine kimse bakmıyor, senin de bakman gerekiyor.', 'Bugün ne kadarına söz verdin?', 1),
  ('wb2', 'tr', 'word_is_bond', 'Hayır demek de bir söz.', '"Yapamam" cümlesini kurmadığın için insanlar sormaya devam ediyor. O cümle bir kırgınlık değil, senin güvenilirliğinin devamı.', 'Bugün bir tanesine hayır de.', 2),
  ('wb3', 'tr', 'word_is_bond', 'Sıraya ben de varım.', 'Kendi işini herkesinki bittikten sonraya koyuyorsun ve o an genelde gelmiyor. Sıraya girmek bencillik değil, sıranın var olması demek.', 'Bugün sırayı kendinden başlat.', 3),
  ('wb4', 'tr', 'word_is_bond', 'Taşıyorum, ama görünsün.', 'Yükü sessizce almak sana doğal geliyor. Kimse ağırlığını bilmediği için de azalmıyor — söylemek şikâyet değil, bilgi.', 'Bugün taşıdığın şeyi bir kişiye söyle.', 4),
  ('ip1', 'tr', 'in_its_place', 'Yerinde duranı da bir yokla.', 'İşleyen şeyi bozmamak senin en sağlam tarafın. Bedeli şu: bozulmuş olanı da yerinde sanıyorsun, çünkü uzun süredir orada.', 'Bugün bir şeyi yokla.', 1),
  ('ip2', 'tr', 'in_its_place', 'Denenmişi seçtim, denemediğimi bilerek.', 'Bildiğin yol seni yanıltmıyor. Yine de bir tercih olduğunu hatırlamak, onu alışkanlık olmaktan çıkarıp karar yapıyor.', 'Bu, seçim mi alışkanlık mı?', 2),
  ('ip3', 'tr', 'in_its_place', 'Bir kere de başka türlü.', 'Değişiklik sana masraf gibi geliyor ve çoğu zaman haklısın. Ama küçük bir sapma, kaybedecek bir şeyin olmadığı yerde ucuz.', 'Bugün bir şeyi başka türlü yap.', 3),
  ('ip4', 'tr', 'in_its_place', 'Sağlamlığım kimseye yük değil.', 'Etrafındakiler sana göre plan yapabiliyor ve bunu sen de biliyorsun. Yalnız şu var: hep aynı yerde durmak, kimsenin sana yeni bir şey sormamasına da yol açıyor.', 'Bugün sana ne sorulsun isterdin?', 4),
  ('iw1', 'tr', 'inwardly', 'Ben de söyleyebilirim.', 'Başkasının halini okumak sende otomatik. Kendi halini söylemek değil — ve söylemediğin sürece kimse sormuyor.', 'Bugün bir cümle de kendin için.', 1),
  ('iw2', 'tr', 'inwardly', 'Fark ettim, artık söylüyorum.', 'Fark etmek yardım etmenin yarısı; diğer yarısı söylemek. İkincisini atladığında yükü tek başına taşımış oluyorsun.', 'Fark ettiğin şeyi bugün söyle.', 2),
  ('iw3', 'tr', 'inwardly', 'Yakınlık iki taraflı.', 'Verdiğin ilgiyi geri istemeyi zorlama sanıyorsun. İstenmediği sürece gelmeyen şeye zorlama denmiyor, yakınlık deniyor.', 'Bugün birinden bir şey iste.', 3),
  ('iw4', 'tr', 'inwardly', 'İçeride kalırsa büyüyor.', 'Söylenmeyen şey sende küçülmüyor, birikiyor. Söylemek onu çözmüyor ama büyümesini durduruyor.', 'Bugün birini içeriden çıkar.', 4);


INSERT INTO day_skeletons (day, locale, title, body, action) VALUES
  (1, 'tr', 'Bir dakika', 'Bugün başlayan şey küçük olmak zorunda. Büyük başlayan her şey ikinci gün pazarlık konusu oluyor; küçük başlayan, sıkıcı olduğu için hayatta kalıyor.', 'Bir dakikanı alacak tek bir şey seç ve bugün onu yap.'),
  (2, 'tr', 'İkinci gün', 'İlk gün heyecanla olur. İkinci gün olmaz — çünkü ikinci günde heyecan yoktur, sadece yapılacak iş vardır. Zincirin gerçekte bugün başlıyor.', 'Dün ne yaptıysan bugün aynısını yap. Daha fazlasını değil.'),
  (3, 'tr', 'Aynı saat', 'Hatırlamak zorunda kaldığın şey unutulur. Aynı saate bağlanan şey hatırlanmaz, sadece olur. Saatin ne olduğu önemli değil, aynı olması önemli.', 'Bugünkü saati not et. Yarın da o saat.'),
  (4, 'tr', 'İlk direnç', 'Dördüncü gün civarında içinden "bugün olmasa da olur" geçer. Bu bir işaret değil, sadece yeniliğin bitmesi. Yenilik bittiğinde geriye kalan şeye alışkanlık deniyor.', 'Bugün canın istemese de yap. Kısa tut, ama yap.'),
  (5, 'tr', 'Kaçırdığın gün', 'Bir gün kaçırmak zinciri bitirmez; kaçırdıktan sonra "nasılsa bozuldu" demek bitirir. Bir gün boşluktur, iki gün karardır.', 'Kaçırdıysan bugün geri dön. Telafi etmeye çalışma, sadece devam et.'),
  (6, 'tr', 'Görünür yer', 'Akılda tutulan şey unutulur, gözün önündeki şey yapılır. İrade dediğimiz şeyin çoğu aslında yerleştirme meselesi.', 'Yapacağın şeyi göreceğin bir yere koy. Kitabı yastığa, şişeyi masaya.'),
  (7, 'tr', 'Bir hafta', 'Yedi gün, bir şeyin sende tuttuğunu anlamak için yeterli. Değişen şey sen değilsin; kararı her gün yeniden vermek zorunda kalmaman.', 'Bu hafta ne fark ettin? Tek cümleyle kendine söyle.'),
  (8, 'tr', 'Çevre', 'Aynı odada, aynı insanlarla, aynı saatte zor olan şey, ortam biraz değişince kolaylaşabiliyor. Zorlanıyorsan sen değil, koşullar ayarlanabilir.', 'Bugün aynı şeyi başka bir yerde ya da başka bir sırada yap.'),
  (9, 'tr', 'Bahane cümlesi', 'Herkesin bir cümlesi var: "yorgunum", "bugün olmaz", "yarın telafi ederim". Cümleyi tanımak onu etkisiz kılmıyor ama görünür kılıyor.', 'Kendi bahane cümleni yaz. Bir daha duyduğunda tanıyacaksın.'),
  (10, 'tr', 'Ölçmeyi bırak', 'Ne kadar ilerlediğini sürekli kontrol etmek, ilerlemeyi yavaşlatan şeylerden biri. Bugün sayacı unut; zaten sayıyor.', 'Bugün ne kadar yaptığını ölçme. Sadece yap.'),
  (11, 'tr', 'Yavaşlama', 'İkinci haftanın ortası, çoğu şeyin sessizce bırakıldığı yer. Sebebi başarısızlık değil, dikkatin başka bir şeye kayması.', 'Bugün süreyi yarıya indir ama atlama. Küçük olan devam eder.'),
  (12, 'tr', 'Anlat', 'Bir şeyi başkasına anlattığında iki şey oluyor: kendin için netleşiyor ve bırakması zorlaşıyor. İkincisi işe yarıyor.', 'Ne yaptığını bir kişiye söyle. Övünmek için değil, söylemiş olmak için.'),
  (13, 'tr', 'Neyi bırakacaksın', 'Yeni bir şey eklemek her zaman bir şeyin yerine geçer. Neyin yerine geçtiğini bilmiyorsan, geri gelecek olan da o.', 'Bu on üç günde neyi daha az yaptığını fark et.'),
  (14, 'tr', 'Bundan sonrası', 'On dört gün bir bitiş değil, ölçüm. Bundan sonra devam eden şey artık bir deneme değil, senin yaptığın bir şey.', 'Yarın da yapacaksan bugün karar ver. Vermezsen yarın karar veremezsin.');


INSERT INTO fragments (archetype_id, ordinal, locale, text) VALUES
  ('quiet_builder', 1, 'tr', 'Sen zaten küçük başlıyorsun. Senin zorlandığın yer başlamak değil, başladığını birine söylemek.'),
  ('quiet_builder', 2, 'tr', 'Heyecan sende zaten yoktu; bugün kaybettiğin bir şey yok. Bu, ikinci günü kolay geçen az sayıdaki insandan biri olman demek.'),
  ('quiet_builder', 3, 'tr', 'Saati kendine sakla, ama bir yere yaz. Aklında tuttuğun şeyleri kimseye söylemediğin için doğrulayan da olmuyor.'),
  ('quiet_builder', 4, 'tr', 'İçinden "bugün olmasa da olur" geçtiğinde kimse fark etmeyecek. Zorluğun burası: seni durduran şey de sessiz.'),
  ('quiet_builder', 5, 'tr', 'Bir gün kaçırdığını yalnız sen bileceksin. O yüzden geri dönme kararını da yalnız sen vereceksin, ve bugün ver.'),
  ('quiet_builder', 6, 'tr', 'Görünür yere koymak sana ters geliyor, biliyorum. Öyleyse yalnız senin gördüğün bir yere koy — ama gördüğün bir yere.'),
  ('quiet_builder', 7, 'tr', 'Bir hafta oldu ve muhtemelen kimse bilmiyor. Bugün bir kişiye söyle; hakkın teslim edilmiyorsa sebebi çoğu zaman bu.'),
  ('quiet_builder', 8, 'tr', 'Ortamın değişmesi seni zorlamaz, sen zaten kendi köşendesin. Asıl soru şu: o köşede tıkandığında kim fark edecek?'),
  ('quiet_builder', 9, 'tr', 'Senin cümlen "henüz hazır değil". Yarım şeyi göstermemek bir standart değil, bir erteleme biçimi.'),
  ('quiet_builder', 10, 'tr', 'Ölçmeyi bırakmak sende kolay; sen zaten ölçmüyorsun. Bugünün zorluğu tersi: yaptığını bir kere görünür kıl.'),
  ('quiet_builder', 11, 'tr', 'İkinci haftanın ortasında sessizce bırakırsan bunu kimse görmez. Görülmemek, bırakmayı ucuzlatıyor.'),
  ('quiet_builder', 12, 'tr', 'Anlatmak senin en zor günün. Övünmek değil bu; birinin bilmesi, tıkandığında sana sorulması demek.'),
  ('quiet_builder', 13, 'tr', 'Bıraktığın şeyin yeri boş kalırsa sende sessizce geri dolar. Bugün o boşluğa bilerek bir şey koy.'),
  ('quiet_builder', 14, 'tr', 'On dört gün boyunca kimse bakmadan yaptın. Bundan sonrası için tek soru: bunu görünür kılmadan ne kadar sürdürebilirsin?'),
  ('spark', 1, 'tr', 'Küçük başlamak sana sıkıcı geliyor, biliyorum. Ama büyük başlayanı üçüncü gün bırakan da sensin.'),
  ('spark', 2, 'tr', 'İkinci gün heyecan bitiyor ve senin motorun heyecan. Bugün, motorun olmadan gidebildiğini görme günü.'),
  ('spark', 3, 'tr', 'Saate bağlamak seni kısıtlıyormuş gibi gelecek. Kısıtlamıyor; seçmeni gereksiz kılıyor, ki asıl yorulduğun şey seçmek.'),
  ('spark', 4, 'tr', '"Bugün olmasa da olur" senin ağzında "daha iyi bir fikrim var" diye çıkar. İkisi aynı cümle.'),
  ('spark', 5, 'tr', 'Bir gün kaçırınca sende hemen yeni bir şey başlatma isteği doğar. Bugün yeni bir şey başlatma; eskisine dön.'),
  ('spark', 6, 'tr', 'Görünür yere koy, ama tek bir şey koy. Yan yana beş hatırlatıcı, hiçbirini hatırlatmıyor.'),
  ('spark', 7, 'tr', 'Bir hafta senin için uzun. Bugüne kadar bitirdiğin şeyleri düşün ve bu listeye bunu da eklemeyi seç.'),
  ('spark', 8, 'tr', 'Ortam değişince senin ilgin tazelenir. Bunu kullan: aynı şeyi başka bir yerde yap, yeni bir şeye başlama.'),
  ('spark', 9, 'tr', 'Senin cümlen "bu artık ilgimi çekmiyor". Doğru olabilir. Ama on dört günün amacı ilgi değil, tekrar.'),
  ('spark', 10, 'tr', 'Ölçmeyi bırak demek sana kolay geliyor. Zor olan şu: ölçmediğin şeyi de sürdürmek.'),
  ('spark', 11, 'tr', 'İkinci haftanın ortası, senin genelde çoktan başka bir şeye geçmiş olduğun yer. Bu sefer geçme.'),
  ('spark', 12, 'tr', 'Anlattığında iş bitmiş gibi hissediyorsun ve orada bırakıyorsun. Bugün anlat, ama bitirmeden.'),
  ('spark', 13, 'tr', 'Yeni bir şey eklemek sende hep bir şeyin yerine geçiyor ve genelde yarım kalanın. Bugün neyin yerine geçtiğini bilerek seç.'),
  ('spark', 14, 'tr', 'On dört gün — senin için asıl yeni olan şey bu. Bundan sonrası, bitirebildiğini bir kez daha kanıtlamak değil, gerek kalmaması.'),
  ('night_watch', 1, 'tr', 'Küçük başlamak sana tedbirsiz geliyor. Değil: küçük olan şey, kötü bir günde de ayakta kalabilen tek şey.'),
  ('night_watch', 2, 'tr', 'İkinci günde heyecan yok ama senin zaten heyecanla değil, tetikle çalışıyorsun. Bugün tetikte olmadan da yapabildiğini gör.'),
  ('night_watch', 3, 'tr', 'Saati seç ve o saatten sonra kontrol etme. Senin için zor olan yapmak değil, yaptıktan sonra bırakmak.'),
  ('night_watch', 4, 'tr', '"Bugün olmasa da olur" sende "bugün iyi bir gün değil" diye çıkar. Genelde haklısın. Bugün haklı olmana rağmen yap.'),
  ('night_watch', 5, 'tr', 'Bir gün kaçırdın diye sistemi baştan kurma. Kaçan gün bir uyarı sinyali değil, sadece bir gün.'),
  ('night_watch', 6, 'tr', 'Görünür yere koyman kolay; senin riskin ona fazla bakmak. Koy ve gün içinde bir kereden fazla kontrol etme.'),
  ('night_watch', 7, 'tr', 'Bir hafta oldu ve hiçbir şey ters gitmedi. Bunu da fark et — sen genelde yalnızca ters gidenleri sayıyorsun.'),
  ('night_watch', 8, 'tr', 'Yeni bir ortam sende önce risk taraması başlatır. Bugün taramayı atla, sadece yap.'),
  ('night_watch', 9, 'tr', 'Senin cümlen "önce şunu halledeyim". O şey her zaman var ve her zaman daha acil görünüyor.'),
  ('night_watch', 10, 'tr', 'Ölçmeyi bırakmak senin için en zor gün. Kontrol etmek sana güvenlik veriyor ama ilerleme vermiyor.'),
  ('night_watch', 11, 'tr', 'İkinci haftada yorgunluk gelir ve sen yorgunluğu bir tehlike işareti sanırsın. Değil; sadece yorgunluk.'),
  ('night_watch', 12, 'tr', 'Anlatmak, nöbeti bir süreliğine devretmek demek. Bugünün asıl görevi bu, cümle kurmak değil.'),
  ('night_watch', 13, 'tr', 'Bıraktığın şey büyük ihtimalle bir kontrol alışkanlığıydı. Onu geri alma; boşluk seni rahatsız etse bile.'),
  ('night_watch', 14, 'tr', 'On dört gün tetikte olmadan da gidebildiğini gösterdi. Bundan sonrası için soru şu: dinlenmeyi de listeye yazacak mısın?'),
  ('table_setter', 1, 'tr', 'Küçük başla ve bu küçük şeyi kimse için yapma. Senin zorluğun boyut değil, sahiplik.'),
  ('table_setter', 2, 'tr', 'İkinci günde heyecan yok ve etrafında da kimse yok. Sen genelde başkası için devam edersin; bugün kendin için et.'),
  ('table_setter', 3, 'tr', 'Saati seçerken kimsenin sana ihtiyaç duymadığı bir saati seç. Yoksa o saat başkasının olur.'),
  ('table_setter', 4, 'tr', '"Bugün olmasa da olur" sende "birine söz vermiştim" diye çıkar. Söz gerçekti; sıra da senindi.'),
  ('table_setter', 5, 'tr', 'Bir gün kaçırdıysan sebebi muhtemelen başkasının bir işiydi. Suçlanacak kimse yok, ama bugün geri dön.'),
  ('table_setter', 6, 'tr', 'Görünür yere koy — başkalarının da göreceği bir yere. Sen kendi işini gizlediğinde herkes seni müsait sanıyor.'),
  ('table_setter', 7, 'tr', 'Bir hafta boyunca kendin için bir şey yaptın. Bu, senin için sandığından büyük bir şey.'),
  ('table_setter', 8, 'tr', 'Ortam değişince sen önce herkesin rahat olup olmadığına bakarsın. Bugün önce kendi işine bak.'),
  ('table_setter', 9, 'tr', 'Senin cümlen "onlar daha çok ihtiyaç duyuyordu". Bazen doğru. On dört gün boyunca hep doğru olamaz.'),
  ('table_setter', 10, 'tr', 'Ölçmeyi bırak, ama kaç kere kendini sıraya en sona koyduğunu bir kere say.'),
  ('table_setter', 11, 'tr', 'İkinci haftada bırakırsan sebebi yorgunluk olmayacak; birine yer açmak olacak.'),
  ('table_setter', 12, 'tr', 'Anlatmak senin için kolay, istemek zor. Bugün anlatırken bir de küçük bir şey iste.'),
  ('table_setter', 13, 'tr', 'Yeni bir şey eklemek bir şeyin yerine geçer. Sende genelde kendine ayırdığın zamanın yerine geçiyor — bu sefer tersini yap.'),
  ('table_setter', 14, 'tr', 'On dört gün kendin için bir şey sürdürdün. Bundan sonrası, bunu kimseden izin almadan sürdürebilmek.'),
  ('fine_worker', 1, 'tr', 'Küçük başla ve küçük kalmasına izin ver. Senin riskin yapmamak değil, yaptığını yeterli saymamak.'),
  ('fine_worker', 2, 'tr', 'İkinci gün heyecansız ve sıradan geçecek. Sıradan olması onu kötü yapmıyor; bu cümleyi bugün bir kere kabul et.'),
  ('fine_worker', 3, 'tr', 'Saati sabitle ve saatin içinde ne kadar iyi olduğuna bakma. Bugün ölçü süre, kalite değil.'),
  ('fine_worker', 4, 'tr', '"Bugün olmasa da olur" sende "bugün iyi olmaz, yarın düzgün yaparım" diye çıkar. Yarın da düzgün olmayacak.'),
  ('fine_worker', 5, 'tr', 'Kaçırdığın gün seni asıl olarak zincirin artık kusursuz olmadığı için rahatsız ediyor. Kusurlu zincir, bitmiş zincirden iyidir.'),
  ('fine_worker', 6, 'tr', 'Görünür yere koy ve düzenini güzelleştirmeye çalışma. Güzelleştirme, senin en sevdiğin erteleme biçimi.'),
  ('fine_worker', 7, 'tr', 'Bir hafta oldu ve muhtemelen hiçbiri istediğin gibi olmadı. Yine de yedi gün oldu.'),
  ('fine_worker', 8, 'tr', 'Ortam değişince sen önce yeni ortamı düzenlemek istersin. Bugün düzenleme, sadece yap.'),
  ('fine_worker', 9, 'tr', 'Senin cümlen "böyle yapmaktansa hiç yapmamak daha iyi". Bu cümle bugüne kadar sana ne kazandırdı?'),
  ('fine_worker', 10, 'tr', 'Ölçmeyi bırakmak sende özellikle zor, çünkü ölçmek senin kalite kontrolün. Bugün kontrolsüz bırak.'),
  ('fine_worker', 11, 'tr', 'İkinci haftada bırakırsan sebebi yorulmak olmayacak; standarda ulaşamamak olacak.'),
  ('fine_worker', 12, 'tr', 'Anlatırken "ama tam istediğim gibi olmadı" ekleme. O ek cümle, işi anlatmayı anlamsız kılıyor.'),
  ('fine_worker', 13, 'tr', 'Yeni bir şey eklemek bir şeyin yerine geçer. Sende genelde bir şeyi tekrar tekrar düzeltmenin yerine geçmeli.'),
  ('fine_worker', 14, 'tr', 'On dört gün, mükemmel olmayan bir şeyi sürdürdün. Bundan sonrası için asıl soru bu: bitmiş olan sende yeterli sayılabilecek mi?'),
  ('compass', 1, 'tr', 'Küçük başla. Sen genelde büyük başlar ve tek başına taşırsın; bu sefer taşınacak bir şey olmasın.'),
  ('compass', 2, 'tr', 'İkinci günde heyecan yok, karar da yok. Senin motorun karar vermek; bugün karar gerektirmeyen bir şeyi sürdür.'),
  ('compass', 3, 'tr', 'Saati bir kere seç ve bir daha gözden geçirme. Optimize etme isteğin bugünkü tek engelin.'),
  ('compass', 4, 'tr', '"Bugün olmasa da olur" sende "daha önemli bir iş var" diye çıkar. Daha önemli iş her zaman var.'),
  ('compass', 5, 'tr', 'Bir gün kaçırınca sen hemen telafi planı kurarsın. Plan kurma; sadece bugünü yap.'),
  ('compass', 6, 'tr', 'Görünür yere koy ve kimseye görev dağıtma. Bu, dağıtılamayacak tek iş.'),
  ('compass', 7, 'tr', 'Bir hafta oldu ve bunu kimseye danışmadan yaptın. Bir sonraki soru: birine danışsan ne değişirdi?'),
  ('compass', 8, 'tr', 'Ortam değişince sen ortamı yönetmeye başlarsın. Bugün yönetme, sadece içinden geç.'),
  ('compass', 9, 'tr', 'Senin cümlen "bu benim işim değil, delege ederim". Bunu edemezsin.'),
  ('compass', 10, 'tr', 'Ölçmeyi bırak. Verim takibi senin doğal aletin ama on dört günün ölçüsü verim değil, süreklilik.'),
  ('compass', 11, 'tr', 'İkinci haftada bırakırsan sebebi ilgisizlik olmayacak; daha acil bir şeyin öne geçmesi olacak.'),
  ('compass', 12, 'tr', 'Anlat, ama karşındakine ne yapması gerektiğini söyleme. Bugün sadece söyle ve sus.'),
  ('compass', 13, 'tr', 'Yeni bir şey eklemek bir şeyin yerine geçer. Sende genelde başkasının işini üstlenmenin yerine geçmeli.'),
  ('compass', 14, 'tr', 'On dört gün tek başına yürüdün ve yürüyebildiğini zaten biliyordun. Bundan sonrası, yanında biriyle yürümenin daha yavaş olmadığını görmek.'),
  ('still_water', 1, 'tr', 'Küçük başla; sen zaten telaş etmiyorsun. Senin riskin panik değil, hiç başlamamak.'),
  ('still_water', 2, 'tr', 'İkinci günde heyecan yok — sende zaten hiç yoktu. O yüzden bugün seni taşıyacak şey karar, his değil.'),
  ('still_water', 3, 'tr', 'Saati net seç. "Bir ara" senin en pahalı cümlen; içinde hiçbir şey yok.'),
  ('still_water', 4, 'tr', '"Bugün olmasa da olur" sende sakin ve makul bir sesle gelir. Sakin olması onu doğru yapmıyor.'),
  ('still_water', 5, 'tr', 'Bir gün kaçırmak seni rahatsız etmedi, biliyorum. Sorun da bu: rahatsız olmayınca geri dönmek için sebep kalmıyor.'),
  ('still_water', 6, 'tr', 'Görünür yere koy. Sen kendi kendine hatırlamayı beklersen o şey hep yarına kalıyor.'),
  ('still_water', 7, 'tr', 'Bir hafta oldu ve muhtemelen hiç zorlanmadın. Şimdi asıl soru: zorlanmadığın şeyi neden bırakmaya bu kadar yakınsın?'),
  ('still_water', 8, 'tr', 'Ortam değişse de sen aynı kalırsın. Bu bir avantaj — bugün onu kullan, ortamı bahane etme.'),
  ('still_water', 9, 'tr', 'Senin cümlen "acelesi yok". Doğru, acelesi yok. Ama on dört günün de acelesi yoktu ve gün dokuz.'),
  ('still_water', 10, 'tr', 'Ölçmeyi bırakmak sana kolay. Bugünün zor kısmı, ölçmediğin şeyi yine de yapmak.'),
  ('still_water', 11, 'tr', 'İkinci haftada bırakırsan bunu kimse fark etmez, sen bile. Sessizce bırakılan şeyler senin en sık kaybettiklerin.'),
  ('still_water', 12, 'tr', 'Anlatmak sana gereksiz gelecek. Gereksiz değil: birinin bilmesi, senin sessizce bırakmanı zorlaştırıyor.'),
  ('still_water', 13, 'tr', 'Bıraktığın şeyi geri almak sana sorun çıkarmaz gibi gelecek. O "sorun değil" hissi, senin en pahalı hissin.'),
  ('still_water', 14, 'tr', 'On dört gün sarsılmadan gittin. Bundan sonrası için soru: bir şey ters gittiğinde bunu söyleyecek misin?'),
  ('deep_diver', 1, 'tr', 'Küçük başla, çünkü senin küçük başlangıcın bile derinleşiyor. Bugün bir dakikayı bir dakika olarak bırak.'),
  ('deep_diver', 2, 'tr', 'İkinci gün sığ ve tatsız geçecek. Sığ olması onu değersiz yapmıyor; her gün derin olamaz.'),
  ('deep_diver', 3, 'tr', 'Saati seç ve bitiş için de bir işaret koy. Senin sorunun girmek değil, çıkmak.'),
  ('deep_diver', 4, 'tr', '"Bugün olmasa da olur" sende bir ağırlık gününde gelir. Ağırlığı taşırken de yapılabilecek kadar küçük seçmiştin, hatırla.'),
  ('deep_diver', 5, 'tr', 'Kaçırdığın günün anlamını çözmeye çalışacaksın. Anlamı yok; sadece kaçırdın.'),
  ('deep_diver', 6, 'tr', 'Görünür yere koy ama üstüne düşünme. Hatırlatıcıyı yorumlamak, hatırlatıcının işini bozuyor.'),
  ('deep_diver', 7, 'tr', 'Bir hafta oldu. Bunun sana ne hissettirdiğini bir cümleyle yaz ve orada bırak — bir sayfa değil, bir cümle.'),
  ('deep_diver', 8, 'tr', 'Yeni bir ortam sende yeni bir şey fark ettiriyor. Bugün fark ettiğini not et ama peşinden gitme.'),
  ('deep_diver', 9, 'tr', 'Senin cümlen "bugün bunu taşıyamam". Bazen doğru. Ama küçük olan şey taşınabilecek kadar küçüktü.'),
  ('deep_diver', 10, 'tr', 'Ölçmeyi bırak — ve ne hissettiğini de ölçme. Bugün sadece yap.'),
  ('deep_diver', 11, 'tr', 'İkinci haftanın ortasında derine inersen gün kaybolur. Bugün yüzeyde kal, bilerek.'),
  ('deep_diver', 12, 'tr', 'Anlatırken kısa tut. Bir sohbete dönüşürse iş anlatmak olmaktan çıkıyor.'),
  ('deep_diver', 13, 'tr', 'Bıraktığın şey muhtemelen anlamlıydı. Anlamlı olması, geri alman gerektiği anlamına gelmiyor.'),
  ('deep_diver', 14, 'tr', 'On dört gün derinliğini kaybetmeden sürdürdün. Bundan sonrası, çıkma anını da bir beceri saymak.'),
  ('own_clock', 1, 'tr', 'Küçük başla, çünkü senin sorunun büyük başlamak değil — ertesi gün hiç başlamamak.'),
  ('own_clock', 2, 'tr', 'İkinci gün, senin dalganın olmadığı ilk gün. Bugün dalgasız da yapabildiğini gör; bütün mesele bu.'),
  ('own_clock', 3, 'tr', 'Saate bağlamak sana yapay gelecek. Yapay; ama senin doğal ritmin geriye bir şey bırakmıyor.'),
  ('own_clock', 4, 'tr', '"Bugün olmasa da olur" sende "bugün gelmedi" diye çıkar. Dalga gelmedi, doğru. Zincir yine de duruyor.'),
  ('own_clock', 5, 'tr', 'Bir gün kaçırınca sende "nasılsa bozuldu" hissi hızlı gelir. Bozulmadı; sadece bir gün.'),
  ('own_clock', 6, 'tr', 'Görünür yere koy. Sen aklında tuttuğunu dalga geçince unutuyorsun.'),
  ('own_clock', 7, 'tr', 'Bir hafta üst üste — senin için asıl yeni olan şey bu, işin kendisi değil.'),
  ('own_clock', 8, 'tr', 'Ortam değişince senin ilgin tazelenir ama süreklilik tazelenmez. Bugün yeni yerde eskisini yap.'),
  ('own_clock', 9, 'tr', 'Senin cümlen "ilham gelince yaparım". On dört gün ilham beklemek için fazla uzun.'),
  ('own_clock', 10, 'tr', 'Ölçmeyi bırak. Sen zaten ölçmüyorsun; bugünün zorluğu ölçmeden de devam etmek.'),
  ('own_clock', 11, 'tr', 'İkinci haftanın ortası, senin dalganın çoktan çekilmiş olduğu yer. Kıyıda kal.'),
  ('own_clock', 12, 'tr', 'Anlat, çünkü seni bekleyen kimse yok. Kimse beklemeyince hatırlatan da olmuyor.'),
  ('own_clock', 13, 'tr', 'Bıraktığın şey dalga geldiğinde çok cazip görünecek. Bugün alma.'),
  ('own_clock', 14, 'tr', 'On dört gün — biriken ilk şey. Bundan sonrası, biriktirmenin dalgadan daha çok şey bıraktığını görmek.'),
  ('contrarian', 1, 'tr', 'Küçük başla. Küçük olması sana yavan gelecek ama bu, kimsenin sana dayatmadığı tek boyut.'),
  ('contrarian', 2, 'tr', 'İkinci günde heyecan yok ve itiraz edecek bir şey de yok. Bugün sadece yapma günü.'),
  ('contrarian', 3, 'tr', 'Saati sen seç. Sana verilen bir saat sende iki gün yaşar, senin seçtiğin saat on dört.'),
  ('contrarian', 4, 'tr', '"Bugün olmasa da olur" sende "bu saçma" diye çıkar. Saçma olabilir; saçma bir şeyi sürdürmek haklı olmaktan zor.'),
  ('contrarian', 5, 'tr', 'Bir gün kaçırınca sistemi tümden reddetme isteği gelir. Reddetme; bir günü kaçırmak bir sistem hatası değil.'),
  ('contrarian', 6, 'tr', 'Görünür yere koy ve kimseye açıklama. Açıklamak zorunda hissetmediğin sürece sürdürmesi kolay.'),
  ('contrarian', 7, 'tr', 'Bir hafta oldu ve bunu kimse sana söyletmedi. Bu, senin kendi kurduğun ilk düzen olabilir.'),
  ('contrarian', 8, 'tr', 'Ortam değişince sen kuralları yeniden sorgularsın. Bugün sorgulama, taşı ve devam et.'),
  ('contrarian', 9, 'tr', 'Senin cümlen "kimseye hesap vermiyorum". Doğru — ve hesap vereceğin tek kişi sensin.'),
  ('contrarian', 10, 'tr', 'Ölçmeyi bırak. Ölçüm sana dışarıdan dayatılmış gibi geliyor zaten; bugün ondan da kurtul.'),
  ('contrarian', 11, 'tr', 'İkinci haftada bırakırsan sebebi ilgisizlik olmayacak; birinin bunu beklemesi olacak.'),
  ('contrarian', 12, 'tr', 'Anlat ama savunma. Neden yaptığını açıklamak zorunda değilsin; söylemek yeterli.'),
  ('contrarian', 13, 'tr', 'Bıraktığın şeyi geri almak bugün bir özgürlük gibi görünecek. Değil, alışkanlık.'),
  ('contrarian', 14, 'tr', 'On dört gün kendi kurduğun bir şeyi sürdürdün. Bundan sonrası, itiraz etmeden de bir şeyin sürebileceğini bilmek.'),
  ('feet_on_ground', 1, 'tr', 'Küçük başla ve somutla: nerede, ne zaman, ne kadar. Üçü belliyse sen zaten yaparsın.'),
  ('feet_on_ground', 2, 'tr', 'İkinci gün sıradan geçecek. Sıradan senin doğal alanın; bugün avantajlı olduğun gün.'),
  ('feet_on_ground', 3, 'tr', 'Saati bir eşyaya bağla, bir niyete değil. Kahve makinesi, kapı, çanta — elle tutulan bir şey.'),
  ('feet_on_ground', 4, 'tr', '"Bugün olmasa da olur" sende "gerek yok" diye çıkar. Gerek olmayabilir; zincirin gereği bugün yapılması.'),
  ('feet_on_ground', 5, 'tr', 'Bir gün kaçırdın. Sebep arama, plan kurma — sadece bugün yap.'),
  ('feet_on_ground', 6, 'tr', 'Görünür yere koy. Bu senin en iyi çalışan yöntemin, çünkü gözünün önündeki şeyi yapıyorsun.'),
  ('feet_on_ground', 7, 'tr', 'Bir hafta oldu ve hiçbir şey soyutlaşmadı. Bu, çoğu insanın beceremediği şey.'),
  ('feet_on_ground', 8, 'tr', 'Ortam değişince senin düzenin bozulur, çünkü düzenin eşyaya bağlı. Bugün yeni ortamda yeni bir eşya seç.'),
  ('feet_on_ground', 9, 'tr', 'Senin cümlen "böyle de oluyor". Oluyor, evet — ve tam bu yüzden hiçbir şey değişmiyor.'),
  ('feet_on_ground', 10, 'tr', 'Ölçmeyi bırak ama işaretlemeyi bırakma. Sende işe yarayan tek soyut şey o kutu.'),
  ('feet_on_ground', 11, 'tr', 'İkinci haftada bırakırsan sebebi zorluk olmayacak; bir sonuç görmemek olacak. Sonuç bu hafta gelmiyor.'),
  ('feet_on_ground', 12, 'tr', 'Anlat, kısa tut. Uzun anlatınca sen de sıkılıyorsun.'),
  ('feet_on_ground', 13, 'tr', 'Bıraktığın şey pratik göründüğü için geri gelmek isteyecek. Bugün alma.'),
  ('feet_on_ground', 14, 'tr', 'On dört gün elindekiyle sürdürdün. Bundan sonrası, elindekinin değişmesine izin vermek.'),
  ('as_is', 1, 'tr', 'Küçük başla ve kimseye anlatma. Bu, senin zaten yaptığın şey — bugün sadece bilerek yap.'),
  ('as_is', 2, 'tr', 'İkinci günde heyecan yok ve seni izleyen de yok. Senin motorun zaten dışarıdan gelmiyordu.'),
  ('as_is', 3, 'tr', 'Saati seç ve kimseye açıklama. Açıklamamak senin hakkın, ama saati seçmek şart.'),
  ('as_is', 4, 'tr', '"Bugün olmasa da olur" sende sessizce gelir. Kimse itiraz etmeyecek; itiraz edecek tek kişi sensin.'),
  ('as_is', 5, 'tr', 'Bir gün kaçırdın ve kimse sormadı. Sormamaları, önemsiz olduğu anlamına gelmiyor.'),
  ('as_is', 6, 'tr', 'Görünür yere koy — kendin için. Senin hatırlatıcın başka kimse olmayacak.'),
  ('as_is', 7, 'tr', 'Bir hafta oldu ve bunu tek başına yaptın. Bu senin gücün; bugün bir kere de zayıf tarafına bak.'),
  ('as_is', 8, 'tr', 'Ortam değişince sen etkilenmezsin. Doğru — ama bu, ortamı hiç kullanmadığın anlamına da geliyor.'),
  ('as_is', 9, 'tr', 'Senin cümlen "kimseye borcum yok". Doğru. Kendine olan sözü de siliyor mu?'),
  ('as_is', 10, 'tr', 'Ölçmeyi bırak. Sen zaten kimseye rapor vermiyorsun; bugün kendine de verme.'),
  ('as_is', 11, 'tr', 'İkinci haftada bırakırsan kimse fark etmez. Fark edilmemek, bırakmayı ucuzlatan şey.'),
  ('as_is', 12, 'tr', 'Anlatmak senin en zor günün. Bir kişi. Kapıyı bir aralık aç.'),
  ('as_is', 13, 'tr', 'Bıraktığın şey seni yormuyordu, o yüzden geri almak kolay gelecek. Alma.'),
  ('as_is', 14, 'tr', 'On dört gün kimseye söylemeden sürdürdün. Bundan sonrası, söylemenin bunu zayıflatmadığını görmek.'),
  ('table_upsetter', 1, 'tr', 'Küçük başla. Senin gücün söylemek; bugünün işi söylemeden yapmak.'),
  ('table_upsetter', 2, 'tr', 'İkinci günde ortada söylenecek bir şey yok, sadece yapılacak bir şey var. Bu sana sıkıcı gelecek.'),
  ('table_upsetter', 3, 'tr', 'Saati seç ve o saatte kimseyle tartışma. Enerjini bugün işe ayır.'),
  ('table_upsetter', 4, 'tr', '"Bugün olmasa da olur" sende bir tartışmanın ardından gelir. Haklı çıkmak yorucudur; zincir onu bilmiyor.'),
  ('table_upsetter', 5, 'tr', 'Kaçırdığın günü savunma. Açıklaman ikna edici olacak ve hiçbir işe yaramayacak.'),
  ('table_upsetter', 6, 'tr', 'Görünür yere koy. Sen söylediğin şeyi taşımayı unutuyorsun, söylemeyi değil.'),
  ('table_upsetter', 7, 'tr', 'Bir hafta boyunca kimseyle çatışmadan bir şey sürdürdün. Bu senin için nadir.'),
  ('table_upsetter', 8, 'tr', 'Ortam değişince senin söyleyecek yeni bir şeyin olur. Bugün söyleme, sadece yap.'),
  ('table_upsetter', 9, 'tr', 'Senin cümlen "burada asıl sorun bu değil". Genelde haklısın ve genelde bu, işi yapmamanın yolu.'),
  ('table_upsetter', 10, 'tr', 'Ölçmeyi bırak. Ölçüm sende bir tartışma malzemesine dönüşüyor.'),
  ('table_upsetter', 11, 'tr', 'İkinci haftada bırakırsan sebebi ilgisizlik değil, daha önemli bir mesele olacak. Her zaman olacak.'),
  ('table_upsetter', 12, 'tr', 'Anlat ama tartışmaya açma. Bugün sadece bir cümle söyle ve orada bırak.'),
  ('table_upsetter', 13, 'tr', 'Bıraktığın şey büyük ihtimalle bir itirazdı. Onu geri alma; sessizlik seni haksız yapmıyor.'),
  ('table_upsetter', 14, 'tr', 'On dört gün söyleyip kaldın. Bundan sonrası, kalmanın söylemekten daha çok şey değiştirdiğini görmek.'),
  ('light_footed', 1, 'tr', 'Küçük başla. Zaten hiçbir şeyi büyütmüyorsun; bugün küçük olması senin lehine.'),
  ('light_footed', 2, 'tr', 'İkinci gün seni yormaz. Senin riskin yorulmak değil, önemsememek.'),
  ('light_footed', 3, 'tr', 'Saati seç ve ciddiye al. Sen her şeyi hafifletiyorsun; bu on dört gün hafifletilmeye gelmiyor.'),
  ('light_footed', 4, 'tr', '"Bugün olmasa da olur" sende gülerek geçer. Gülerek geçen şeyler sende bir daha dönmüyor.'),
  ('light_footed', 5, 'tr', 'Bir gün kaçırmak sende iz bırakmaz. Sorun tam bu: iz bırakmayan şey düzeltilmiyor.'),
  ('light_footed', 6, 'tr', 'Görünür yere koy. Senin için hatırlatıcı bir uyarı değil, sadece bir dokunuş.'),
  ('light_footed', 7, 'tr', 'Bir hafta oldu ve hiç zorlanmadın. Bunu bir başarı say — sen genelde saymıyorsun.'),
  ('light_footed', 8, 'tr', 'Yeni bir ortam sende hiçbir şeyi değiştirmez. Bugün bunu avantaja çevir.'),
  ('light_footed', 9, 'tr', 'Senin cümlen "olmasa da olur". Bugün o cümleyi bir kere reddet.'),
  ('light_footed', 10, 'tr', 'Ölçmeyi bırak. Zaten ölçmüyorsun; bugün ölçmeden de ciddiye almayı dene.'),
  ('light_footed', 11, 'tr', 'İkinci haftada bırakırsan bunu bir kayıp saymayacaksın. Saymadığın kayıplar en çok biriktirdiklerin.'),
  ('light_footed', 12, 'tr', 'Anlat. Sen genelde anlatmaya değmez bulursun; bugün değer bul.'),
  ('light_footed', 13, 'tr', 'Bıraktığın şeyi geri almak sana kolay gelecek, çünkü hiçbiri ağır değil. Ağır olmaması onu önemsiz yapmıyor.'),
  ('light_footed', 14, 'tr', 'On dört gün önemsemeyi denedin. Bundan sonrası, neyin gerçekten büyük olduğunu zamanında fark etmek.'),
  ('full_glass', 1, 'tr', 'Küçük başla ve tek şey seç. Senin zorluğun yapmak değil, hangisini önce yapacağın.'),
  ('full_glass', 2, 'tr', 'İkinci günde her şey aynı anda gelecek. Bugün sadece birini al.'),
  ('full_glass', 3, 'tr', 'Saati seç, çünkü seçilmemiş saat sende bütün günü kaplıyor.'),
  ('full_glass', 4, 'tr', '"Bugün olmasa da olur" sende taşma anında gelir. O an geçicidir; karar değil.'),
  ('full_glass', 5, 'tr', 'Bir gün kaçırdın ve bu sende büyük hissettirdi. Büyük değil; bir gün.'),
  ('full_glass', 6, 'tr', 'Görünür yere koy ama tek bir şey koy. Beş hatırlatıcı sende beş yük demek.'),
  ('full_glass', 7, 'tr', 'Bir hafta oldu ve taşmadan gittin. Bunu fark et; sen genelde yalnızca taştığın günleri sayıyorsun.'),
  ('full_glass', 8, 'tr', 'Ortam değişince sende her şey bir kat daha yüksek sesle gelir. Bugün sesi kısmayı değil, tek şeye bakmayı dene.'),
  ('full_glass', 9, 'tr', 'Senin cümlen "şu an çok şey var". Var, doğru. Ve seçtiğin şey bir dakikalıktı.'),
  ('full_glass', 10, 'tr', 'Ölçmeyi bırak. Ölçüm sende bir yük daha demek.'),
  ('full_glass', 11, 'tr', 'İkinci haftada bırakırsan sebebi ilgisizlik olmayacak; dolmak olacak. Bugün boşaltma günü değil, tek şey günü.'),
  ('full_glass', 12, 'tr', 'Anlat, ama tek cümleyle. Uzatınca hepsi geri geliyor.'),
  ('full_glass', 13, 'tr', 'Bıraktığın şey bugün hafif görünecek. Geri alma; hafif görünen şeyler sende çabuk ağırlaşıyor.'),
  ('full_glass', 14, 'tr', 'On dört gün taşmadan sürdürdün. Bundan sonrası, taşmamak için harcadığın enerjiyi işin kendisine ayırmak.'),
  ('word_is_bond', 1, 'tr', 'Küçük başla. Sen söz verdiğin şeyi yaparsın; o yüzden bugün kendine küçük bir söz ver.'),
  ('word_is_bond', 2, 'tr', 'İkinci günde kimse seni izlemiyor. Senin için asıl sınav bu: kimseye verilmemiş söz.'),
  ('word_is_bond', 3, 'tr', 'Saati seç ve o saati kimseye açtırma. Senin saatlerin genelde başkalarının işgalinde.'),
  ('word_is_bond', 4, 'tr', '"Bugün olmasa da olur" sende "başkasına söz vermiştim" diye çıkar. O söz gerçek; bu da öyle.'),
  ('word_is_bond', 5, 'tr', 'Bir gün kaçırdın ve kendine verdiğin sözü ilk kez bozdun. Bunu bir başarısızlık değil, bir bilgi say.'),
  ('word_is_bond', 6, 'tr', 'Görünür yere koy. Sen listendeki şeyleri yaparsın; sorun listeye kendini yazmaman.'),
  ('word_is_bond', 7, 'tr', 'Bir hafta boyunca kendine verdiğin sözü tuttun. Bu, senin en az alıştığın söz türü.'),
  ('word_is_bond', 8, 'tr', 'Ortam değişince sana daha çok iş gelir, çünkü güvenilir olduğun bilinir. Bugün bir tanesine hayır de.'),
  ('word_is_bond', 9, 'tr', 'Senin cümlen "önce şunu halledeyim, sonra". Sonra hiç gelmiyor.'),
  ('word_is_bond', 10, 'tr', 'Ölçmeyi bırak. Sen zaten kendini ölçüyorsun ve genelde sert ölçüyorsun.'),
  ('word_is_bond', 11, 'tr', 'İkinci haftada bırakırsan sebebi tükenmek olacak. Tükenmeden önce hayır demeyi dene.'),
  ('word_is_bond', 12, 'tr', 'Anlat ve bir şey iste. İstemek senin en zor cümlen.'),
  ('word_is_bond', 13, 'tr', 'Yeni bir şey eklemek bir şeyin yerine geçer. Sende başkasının işinin yerine geçmeli, kendi dinlenmenin değil.'),
  ('word_is_bond', 14, 'tr', 'On dört gün kendine verdiğin sözü tuttun. Bundan sonrası, sıraya kendini de yazmayı alışkanlık yapmak.'),
  ('in_its_place', 1, 'tr', 'Küçük başla. Yeni olan seni zorlamıyorsa sebebi küçük olması; bugün bu iyi bir şey.'),
  ('in_its_place', 2, 'tr', 'İkinci gün dünle aynı geçecek. Aynılık senin işine geliyor — çoğu insan için zor olan gün bu.'),
  ('in_its_place', 3, 'tr', 'Saati seç ve bir daha değiştirme. Sen zaten değiştirmezsin.'),
  ('in_its_place', 4, 'tr', '"Bugün olmasa da olur" sende "bugün düzen bozuldu" diye çıkar. Düzen bozulduğunda da yapılabilir.'),
  ('in_its_place', 5, 'tr', 'Bir gün kaçırdın ve bu senin için düzenin kırılması demek. Kırılmadı; bir gün eksik kaldı.'),
  ('in_its_place', 6, 'tr', 'Görünür yere koy ve yerini bir daha değiştirme.'),
  ('in_its_place', 7, 'tr', 'Bir hafta oldu ve hiçbir şey sarsılmadı. Şimdi asıl soru: bu on dört günde neyin değişmesini istiyordun?'),
  ('in_its_place', 8, 'tr', 'Ortam değişince sen zorlanırsın. Bugün eski yerinde yapmayı bırak, bir kere yeni yerde yap.'),
  ('in_its_place', 9, 'tr', 'Senin cümlen "böyle iyi zaten". Bazen doğru. On dört gün boyunca hep doğru olamaz.'),
  ('in_its_place', 10, 'tr', 'Ölçmeyi bırak. Ölçmek sende her şeyi eski hâline getirme isteği doğuruyor.'),
  ('in_its_place', 11, 'tr', 'İkinci haftada bırakırsan sebebi zorluk olmayacak; eskisinin daha rahat olması olacak.'),
  ('in_its_place', 12, 'tr', 'Anlat. Anlatmak seni değiştirmez ama söylediğin şey bir kere dışarı çıkar.'),
  ('in_its_place', 13, 'tr', 'Yeni bir şey eklemek bir şeyin yerine geçer, ve sende hiçbir şey yerinden oynamıyor. Bugün bir şeyi bilerek oynat.'),
  ('in_its_place', 14, 'tr', 'On dört gün aynı yerde durmadın. Bundan sonrası, değişmesi gerekeni de fark edebilmek.'),
  ('inwardly', 1, 'tr', 'Küçük başla ve bu kez kendin için. Sen genelde küçük şeyleri başkaları için yapıyorsun.'),
  ('inwardly', 2, 'tr', 'İkinci günde kimse senden bir şey beklemiyor. Bugünkü tek beklenti seninki.'),
  ('inwardly', 3, 'tr', 'Saati seç. Sen genelde başkalarının saatlerine göre yaşıyorsun; bu saat sana ait.'),
  ('inwardly', 4, 'tr', '"Bugün olmasa da olur" sende sessizce ve suçluluk duymadan gelir. Duymuyorsun çünkü kimseyi üzmüyorsun — kendin hariç.'),
  ('inwardly', 5, 'tr', 'Bir gün kaçırdın ve kimseye söylemedin. Söylemeden de geri dönebilirsin, ama bugün dön.'),
  ('inwardly', 6, 'tr', 'Görünür yere koy. Senin içinde tuttuğun şeyler dışarı çıkmıyor, hatırlatıcılar da öyle.'),
  ('inwardly', 7, 'tr', 'Bir hafta boyunca kendin için bir şey taşıdın. Sen genelde başkasının yükünü taşıyorsun.'),
  ('inwardly', 8, 'tr', 'Ortam değişince sen önce herkesin nasıl olduğunu okursun. Bugün önce kendine bak.'),
  ('inwardly', 9, 'tr', 'Senin cümlen "birinin canı sıkkındı". Fark etmiştin, evet. Sıra sana geldiğinde kim fark edecek?'),
  ('inwardly', 10, 'tr', 'Ölçmeyi bırak. Sen zaten içinden ölçüyorsun ve kimseye söylemiyorsun.'),
  ('inwardly', 11, 'tr', 'İkinci haftada bırakırsan bunu kimse bilmeyecek. Bilinmemek, senin en sık kullandığın bırakma yolu.'),
  ('inwardly', 12, 'tr', 'Anlat. Bugünün asıl işi bu: yardım tek yönlü akmasın diye bir kere ters yöne aç.'),
  ('inwardly', 13, 'tr', 'Bıraktığın şey muhtemelen birine ayırdığın zamandı. Onu geri alma.'),
  ('inwardly', 14, 'tr', 'On dört gün kendin için taşıdın. Bundan sonrası, fark ettiğini söylemeyi de öğrenmek.');


INSERT INTO connectors (id, locale, text) VALUES
  ('c1', 'tr', 'Sende bunun karşılığı şu.'),
  ('c2', 'tr', 'Senin için zor olan kısmı ise başka.'),
  ('c3', 'tr', 'Bu, sana özellikle şöyle uğruyor.'),
  ('c4', 'tr', 'Aynı şeyin sendeki hâli daha farklı.'),
  ('c5', 'tr', 'Şunu da eklemek gerek, çünkü seni ilgilendiren tarafı bu.'),
  ('c6', 'tr', 'Bunun sende nereye denk düştüğüne bak.'),
  ('c7', 'tr', 'Sen bu cümleyi muhtemelen başka bir yerinden okuyorsun.'),
  ('c8', 'tr', 'Senin durumunda asıl mesele burada.'),
  ('c9', 'tr', 'Bunu senin için biraz daha açalım.'),
  ('c10', 'tr', 'Ve sende bu, tanıdık bir yerden geliyor.');


INSERT INTO report_sections (section, locale, dimension) VALUES
  (1, 'tr', 'CONSCIENTIOUSNESS'),
  (2, 'tr', 'EXTRAVERSION'),
  (3, 'tr', 'OPENNESS'),
  (4, 'tr', 'NEUROTICISM'),
  (5, 'tr', 'AGREEABLENESS');

INSERT INTO support_texts (kind, key, locale, heading, body, ordinal) VALUES
  ('faq', 'data_on_device', 'tr', 'Verilerim nerede tutuluyor?', 'Arketibin, zincirin ve görevlerin sunucuda, cihazına bağlı bir kimlikle — isminle değil. Test cevapların saklanmıyor: puanlanıp unutuluyorlar.', 1),
  ('faq', 'no_account', 'tr', 'Neden hesap açmıyorum?', 'Çünkü gerekmiyor. Hesapsız başlamak, seni bir e-posta vermeye zorlamadan kullanmanın tek yolu. Bunun bedeli aşağıdaki maddede yazıyor.', 2),
  ('faq', 'lost_data', 'tr', 'Telefonumu değiştirirsem ne olur?', 'Zincirin gider. Kayıtlar cihazına bağlı ve hesap olmadığı için yeni telefona taşıyacak bir yer yok — bu, hesapsız çalışmanın bedeli.', 3),
  ('faq', 'why_wait', 'tr', 'Neden hemen yeni bir envanter dolduramıyorum?', 'Kişilik iki günde değişmez. Arka arkaya çözülen bir envanter, cevabı değil ruh halini ölçer. Bekleme süresi sonucun bir anlamı olsun diye.', 4),
  ('faq', 'accuracy', 'tr', 'Sonuç ne kadar doğru?', 'Kısa bir form, kaba bir çözünürlük verir. Arketip bilimsel bir kategori değil, beş boyutlu bir profilin editöryal yorumu. Yöntem sayfasında sınırlılıkları tek tek yazdık.', 5),
  ('faq', 'not_me', 'tr', 'Arketip bana uymadı, ne yapayım?', 'Sonuç ekranındaki "bana uymadı" bağlantısını kullan. Hangi arketibin ne sıklıkla reddedildiği, eşleme tablosunu düzeltmek için elimizdeki tek sinyal.', 6),
  ('faq', 'chain_broken', 'tr', 'Zincirim kırıldı, geri gelir mi?', 'Ayda bir telafi hakkın var ve tek bir kaçan günü kapatır. İki gün kaçtıysa kapatmaz — kapatsaydı zincirin bir anlamı kalmazdı.', 7),
  ('faq', 'offline', 'tr', 'İnternetsiz çalışır mı?', 'Günü işaretlemek çalışır, bağlantı gelince gönderilir. Günlük içerik ve görevler sunucudan geliyor, o yüzden onlar için bağlantı gerekiyor.', 8),
  ('faq', 'notifications_off', 'tr', 'Bildirimlere izin vermedim, zincir çalışır mı?', 'Çalışır. Sadece hatırlatma gelmez; günü kendin işaretlersin. iOS izni bir kez sorar, sonrasında yalnızca sistem ayarlarından açılır.', 9),
  ('faq', 'reminder_time', 'tr', 'Hatırlatma saatini değiştirebilir miyim?', 'Ayarlar ekranından. Günde en fazla bir hatırlatma gelir ve 22:00 ile 08:00 arasında hiç gelmez.', 10),
  ('faq', 'too_many', 'tr', 'Neden bazen hiç bildirim gelmiyor?', 'Üst üste üç bildirimi açmazsan sıklık kendiliğinden düşer. Görmezden gelinen bir hatırlatıcının çözümü dördüncüsü değil.', 11),
  ('faq', 'delete_data', 'tr', 'Verilerimi sildirebilir miyim?', 'Ayarlar → Gizlilik → Verilerimi sil. Arketibin, zincirin ve görevlerin silinir. Cihaz kimliğin ve kullandığın hak sayısı kalır; silip yeniden yükleyerek hak kazanılmasın diye.', 12),
  ('faq', 'cost', 'tr', 'Ücretli mi?', 'Envanter, sonuç, kart, zincir ve günlük görevler ücretsiz. Derin rapor ve arketip galerisi premium.', 13),
  ('faq', 'game', 'tr', 'Oyun ne işe yarıyor?', 'Eğlence, ve haftanın en iyi 10 skoru bir derin rapor kazanıyor.', 14),
  ('faq', 'share_card', 'tr', 'Paylaştığım kartta ne görünüyor?', 'Arketibinin adı ve mottosu. Cevapların, puanların ve cihaz kimliğin kartta yok.', 15),
  ('faq', 'contact', 'tr', 'Size nasıl ulaşırım?', 'Ayarlar → Geri bildirim. E-posta bırakmak zorunda değilsin; bırakmazsan okuruz ama cevap yazamayız.', 16),
  ('privacy', 'privacy_1', 'tr', NULL, 'Adın, e-postan ya da telefon numaran istenmiyor. Hesap yok.', 1),
  ('privacy', 'privacy_2', 'tr', NULL, 'Tutulan kimlik seni değil, telefonu tanıyor.', 2),
  ('privacy', 'privacy_3', 'tr', NULL, 'Cevapların puanlanıp sonucu döndürülüyor; cevapların saklanmıyor.', 3),
  ('privacy', 'privacy_4', 'tr', NULL, 'Arketibin, zincirin ve işaretlediğin görevler o kimliğe bağlı duruyor.', 4),
  ('privacy', 'privacy_5', 'tr', NULL, 'Hatırlatıcı saatin ve yarım kalmış testin yalnızca telefonunda.', 5),
  ('privacy', 'privacy_6', 'tr', NULL, 'Ölçüm kendi sunucumuzda: üçüncü parti araç yok, reklam kimliği yok.', 6),
  ('privacy', 'privacy_7', 'tr', NULL, 'Paylaştığın kartta yalnızca arketibinin adı ve mottosu var.', 7),
  ('deletion', 'goes_1', 'tr', 'goes', 'Arketibin ve aldığın mottolar', 1),
  ('deletion', 'goes_2', 'tr', 'goes', 'Zincirin ve işaretlediğin günler', 2),
  ('deletion', 'goes_3', 'tr', 'goes', 'Yaptığın görevler', 3),
  ('deletion', 'stays_4', 'tr', 'stays', 'Cihaz kimliğin', 4),
  ('deletion', 'stays_5', 'tr', 'stays', 'Kullandığın hak sayısı', 5),
  ('deletion', 'counter_reason_6', 'tr', 'counter_reason', 'Kullanım hakkı sayacı, suistimali önlemek için saklanır: silip yeniden yükleyerek hak kazanılamaz. Bu sayaç kim olduğunu değil, kaç kez kullandığını bilir.', 6),
  ('deletion', 'answers_note_7', 'tr', 'answers_note', 'Test cevapların zaten saklanmıyor; puanlanıp unutuluyorlar.', 7);
