// GENERATED by tool/coverage_helper.sh — do not edit by hand.
//
// Exists so that files without tests appear in coverage as 0% instead
// of not appearing at all. See the script for the full reasoning.
//
// ignore_for_file: unused_import

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:wallet/app.dart';
import 'package:wallet/config/app_crash_listener.dart';
import 'package:wallet/config/env.dart';
import 'package:wallet/config/injectable.dart';
import 'package:wallet/config/modules/storage_module.dart';
import 'package:wallet/features/about/about_info.dart';
import 'package:wallet/features/about/presentation/page/about_page.dart';
import 'package:wallet/features/finance/application/budget/budget_cubit.dart';
import 'package:wallet/features/finance/application/budget/budget_state.dart';
import 'package:wallet/features/finance/application/dashboard/dashboard_cubit.dart';
import 'package:wallet/features/finance/application/dashboard/dashboard_state.dart';
import 'package:wallet/features/finance/application/entry/entry_cubit.dart';
import 'package:wallet/features/finance/application/entry/entry_state.dart';
import 'package:wallet/features/finance/application/history/history_bloc.dart';
import 'package:wallet/features/finance/application/history/history_effect.dart';
import 'package:wallet/features/finance/application/history/history_event.dart';
import 'package:wallet/features/finance/application/history/history_state.dart';
import 'package:wallet/features/finance/default_categories.dart';
import 'package:wallet/features/finance/domain/models/budget.dart';
import 'package:wallet/features/finance/domain/models/category.dart';
import 'package:wallet/features/finance/domain/models/currency.dart';
import 'package:wallet/features/finance/domain/models/money.dart';
import 'package:wallet/features/finance/domain/models/money_transaction.dart';
import 'package:wallet/features/finance/domain/repository/budget_repository.dart';
import 'package:wallet/features/finance/domain/repository/category_repository.dart';
import 'package:wallet/features/finance/domain/repository/transaction_repository.dart';
import 'package:wallet/features/finance/domain/rules/amount_input.dart';
import 'package:wallet/features/finance/domain/rules/budget_evaluator.dart';
import 'package:wallet/features/finance/domain/rules/clock.dart';
import 'package:wallet/features/finance/domain/rules/currency_usage.dart';
import 'package:wallet/features/finance/domain/rules/month_period.dart';
import 'package:wallet/features/finance/domain/rules/monthly_summary.dart';
import 'package:wallet/features/finance/domain/rules/transaction_filter.dart';
import 'package:wallet/features/finance/presentation/format/category_icons.dart';
import 'package:wallet/features/finance/presentation/format/money_format.dart';
import 'package:wallet/features/finance/presentation/page/budget_page.dart';
import 'package:wallet/features/finance/presentation/page/dashboard_page.dart';
import 'package:wallet/features/finance/presentation/page/history_page.dart';
import 'package:wallet/features/finance/presentation/page/main_page.dart';
import 'package:wallet/features/finance/presentation/page/transaction_entry_page.dart';
import 'package:wallet/features/finance/presentation/views/budget_editor_sheet.dart';
import 'package:wallet/features/finance/presentation/views/budget_progress_tile.dart';
import 'package:wallet/features/finance/presentation/views/budget_view.dart';
import 'package:wallet/features/finance/presentation/views/category_pie_chart.dart';
import 'package:wallet/features/finance/presentation/views/currency_chips.dart';
import 'package:wallet/features/finance/presentation/views/dashboard_view.dart';
import 'package:wallet/features/finance/presentation/views/empty_state.dart';
import 'package:wallet/features/finance/presentation/views/history_filter_sheet.dart';
import 'package:wallet/features/finance/presentation/views/history_view.dart';
import 'package:wallet/features/finance/presentation/views/month_switcher.dart';
import 'package:wallet/features/finance/presentation/views/summary_header.dart';
import 'package:wallet/features/finance/presentation/views/transaction_entry_view.dart';
import 'package:wallet/features/finance/presentation/views/transaction_tile.dart';
import 'package:wallet/features/settings/application/settings_cubit.dart';
import 'package:wallet/features/settings/domain/repository/settings_repository.dart';
import 'package:wallet/features/settings/domain/theme_preference.dart';
import 'package:wallet/features/settings/presentation/page/settings_page.dart';
import 'package:wallet/features/settings/presentation/theme_preference_label.dart';
import 'package:wallet/features/settings/presentation/views/language_section.dart';
import 'package:wallet/features/settings/presentation/views/setting_option_tile.dart';
import 'package:wallet/features/startup/presentation/splash_view.dart';
import 'package:wallet/features/startup/presentation/startup_page.dart';
import 'package:wallet/infrastructure/adapter/bootstrap/bootstrap_adapter.dart';
import 'package:wallet/infrastructure/dev/demo_transactions.dart';
import 'package:wallet/infrastructure/repository/budget_repository_impl.dart';
import 'package:wallet/infrastructure/repository/category_repository_impl.dart';
import 'package:wallet/infrastructure/repository/dto/budget_dto.dart';
import 'package:wallet/infrastructure/repository/dto/category_dto.dart';
import 'package:wallet/infrastructure/repository/dto/transaction_dto.dart';
import 'package:wallet/infrastructure/repository/settings_repository_impl.dart';
import 'package:wallet/infrastructure/repository/transaction_repository_impl.dart';
import 'package:wallet/infrastructure/storage/hive_collection.dart';
import 'package:wallet/infrastructure/storage/wallet_storage.dart';
import 'package:wallet/main.dart';
import 'package:wallet/route/app_router.dart';
import 'package:wallet/theme/app_mark.dart';
import 'package:wallet/theme/app_theme.dart';

void main() {
  test('imports every library, so untested files count as 0%', () {
    final imported = RegExp("^import 'package:wallet/(.+)';", multiLine: true)
        .allMatches(File('test/coverage_helper_test.dart').readAsStringSync())
        .map((match) => 'lib/${match.group(1)}')
        .toSet();

    final onDisk = Directory('lib')
        .listSync(recursive: true)
        .whereType<File>()
        .map((file) => file.path)
        .where((path) => path.endsWith('.dart'))
        .where((path) => !path.startsWith('lib/generated/'))
        .where(
          (path) => !RegExp(r'\.(g|gr|freezed|config)\.dart$').hasMatch(path),
        )
        .toSet();

    expect(
      onDisk.difference(imported),
      isEmpty,
      reason:
          'these libraries are missing from the coverage helper — run '
          '`melos run coverage:helper`',
    );
  });
}
