// GENERATED by tool/coverage_helper.sh — do not edit by hand.
//
// Exists so that files without tests appear in coverage as 0% instead
// of not appearing at all. See the script for the full reasoning.
//
// ignore_for_file: unused_import

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:motto/app.dart';
import 'package:motto/config/app_crash_listener.dart';
import 'package:motto/config/app_ready.dart';
import 'package:motto/config/env.dart';
import 'package:motto/config/injectable.dart';
import 'package:motto/config/reported.dart';
import 'package:motto/config/storage_module.dart';
import 'package:motto/features/chain/application/chain_cubit.dart';
import 'package:motto/features/chain/application/chain_repository.dart';
import 'package:motto/features/chain/application/chain_state.dart';
import 'package:motto/features/chain/application/chain_store.dart';
import 'package:motto/features/chain/application/reminder_scheduler.dart';
import 'package:motto/features/chain/domain/chain.dart';
import 'package:motto/features/chain/domain/reminder.dart';
import 'package:motto/features/chain/domain/reminder_copy.dart';
import 'package:motto/features/chain/domain/reminder_plan.dart';
import 'package:motto/features/chain/domain/turkish_reminder_copy.dart';
import 'package:motto/features/chain/presentation/period_done_page.dart';
import 'package:motto/features/chain/presentation/widgets/chain_strip.dart';
import 'package:motto/features/content/application/content_repository.dart';
import 'package:motto/features/content/application/content_store.dart';
import 'package:motto/features/daily/application/daily_cubit.dart';
import 'package:motto/features/daily/application/daily_state.dart';
import 'package:motto/features/daily/application/daily_widget.dart';
import 'package:motto/features/daily/domain/content_pack.dart';
import 'package:motto/features/daily/domain/daily_assembler.dart';
import 'package:motto/features/daily/domain/daily_content.dart';
import 'package:motto/features/daily/presentation/today_page.dart';
import 'package:motto/features/daily/presentation/widgets/archetype_row.dart';
import 'package:motto/features/daily/presentation/widgets/day_block.dart';
import 'package:motto/features/daily/presentation/widgets/game_row.dart';
import 'package:motto/features/daily/presentation/widgets/motto_block.dart';
import 'package:motto/features/daily/presentation/widgets/period_done_banner.dart';
import 'package:motto/features/daily/presentation/widgets/tomorrow_line.dart';
import 'package:motto/features/daily/presentation/widgets/yesterday_line.dart';
import 'package:motto/features/game/application/game_store.dart';
import 'package:motto/features/game/domain/sorting_game.dart';
import 'package:motto/features/game/presentation/game_over_page.dart';
import 'package:motto/features/game/presentation/game_page.dart';
import 'package:motto/features/game/presentation/game_rules_page.dart';
import 'package:motto/features/game/presentation/open_game.dart';
import 'package:motto/features/mascot/application/mascot_attention.dart';
import 'package:motto/features/mascot/application/mascot_controller.dart';
import 'package:motto/features/mascot/application/mascot_placement.dart';
import 'package:motto/features/mascot/application/mascot_store.dart';
import 'package:motto/features/mascot/application/rive_mascot_controller.dart';
import 'package:motto/features/mascot/presentation/mascot.dart';
import 'package:motto/features/mascot/presentation/mascot_host.dart';
import 'package:motto/features/mascot/presentation/mascot_route_observer.dart';
import 'package:motto/features/onboarding/application/onboarding_store.dart';
import 'package:motto/features/onboarding/presentation/onboarding_page.dart';
import 'package:motto/features/profile/application/profile_cubit.dart';
import 'package:motto/features/profile/presentation/archive_page.dart';
import 'package:motto/features/profile/presentation/deep_report_page.dart';
import 'package:motto/features/profile/presentation/gallery_page.dart';
import 'package:motto/features/profile/presentation/profile_page.dart';
import 'package:motto/features/result/application/card_exporter.dart';
import 'package:motto/features/result/presentation/report_page.dart';
import 'package:motto/features/result/presentation/result_page.dart';
import 'package:motto/features/result/presentation/share_card_page.dart';
import 'package:motto/features/result/presentation/widgets/basis_section.dart';
import 'package:motto/features/result/presentation/widgets/share_card.dart';
import 'package:motto/features/shell/presentation/shell_page.dart';
import 'package:motto/features/shell/presentation/widgets/floating_nav_bar.dart';
import 'package:motto/features/startup/presentation/startup_page.dart';
import 'package:motto/features/support/application/data_deletion.dart';
import 'package:motto/features/support/application/feedback_cubit.dart';
import 'package:motto/features/support/application/last_archetype.dart';
import 'package:motto/features/support/application/support_context.dart';
import 'package:motto/features/support/application/support_copy_cubit.dart';
import 'package:motto/features/support/domain/method_text.dart';
import 'package:motto/features/support/presentation/data_deletion_page.dart';
import 'package:motto/features/support/presentation/faq_page.dart';
import 'package:motto/features/support/presentation/feedback_page.dart';
import 'package:motto/features/support/presentation/method_page.dart';
import 'package:motto/features/support/presentation/privacy_page.dart';
import 'package:motto/features/support/presentation/settings_page.dart';
import 'package:motto/features/support/presentation/widgets/rejection_sheet.dart';
import 'package:motto/features/tasks/application/task_cubit.dart';
import 'package:motto/features/tasks/presentation/daily_tasks_page.dart';
import 'package:motto/features/tasks/presentation/motto_detail_page.dart';
import 'package:motto/features/tasks/presentation/period_report_page.dart';
import 'package:motto/features/tasks/presentation/task_detail_page.dart';
import 'package:motto/features/tasks/presentation/widgets/day_closing.dart';
import 'package:motto/features/tasks/presentation/widgets/task_card.dart';
import 'package:motto/features/test/application/test_cubit.dart';
import 'package:motto/features/test/application/test_draft.dart';
import 'package:motto/features/test/application/test_effect.dart';
import 'package:motto/features/test/application/test_state.dart';
import 'package:motto/features/test/presentation/calculating_page.dart';
import 'package:motto/features/test/presentation/question_page.dart';
import 'package:motto/features/test/presentation/widgets/glimpse_sheet.dart';
import 'package:motto/features/test/presentation/widgets/likert_scale.dart';
import 'package:motto/features/test/presentation/widgets/test_progress.dart';
import 'package:motto/features/welcome/presentation/welcome_page.dart';
import 'package:motto/infrastructure/analytics/analytics.dart';
import 'package:motto/infrastructure/analytics/event_queue.dart';
import 'package:motto/infrastructure/analytics/motto_event.dart';
import 'package:motto/infrastructure/api/api_clients.dart';
import 'package:motto/infrastructure/api/renewing_client.dart';
import 'package:motto/infrastructure/bootstrap/bootstrap_adapter.dart';
import 'package:motto/infrastructure/identity/device_identity.dart';
import 'package:motto/infrastructure/identity/device_identity_impl.dart';
import 'package:motto/infrastructure/notifications/local_reminder_scheduler.dart';
import 'package:motto/infrastructure/session/device_session.dart';
import 'package:motto/infrastructure/session/token_store.dart';
import 'package:motto/main.dart';
import 'package:motto/route/app_router.dart';
import 'package:motto/route/reloads_on_return.dart';
import 'package:motto/theme/motto_loading.dart';
import 'package:motto/theme/motto_palette.dart';
import 'package:motto/theme/motto_theme.dart';

void main() {
  test('imports every library, so untested files count as 0%', () {
    final imported = RegExp("^import 'package:motto/(.+)';", multiLine: true)
        .allMatches(File('test/coverage_helper_test.dart').readAsStringSync())
        .map((match) => 'lib/${match.group(1)}')
        .toSet();

    final onDisk = Directory('lib')
        .listSync(recursive: true)
        .whereType<File>()
        .map((file) => file.path)
        .where((path) => path.endsWith('.dart'))
        .where((path) => !path.startsWith('lib/generated/'))
        .where(
          (path) => !RegExp(r'\.(g|gr|freezed|config)\.dart$').hasMatch(path),
        )
        .toSet();

    expect(
      onDisk.difference(imported),
      isEmpty,
      reason:
          'these libraries are missing from the coverage helper — run '
          '`melos run coverage:helper`',
    );
  });
}
