// GENERATED by tool/coverage_helper.sh — do not edit by hand.
//
// Exists so that files without tests appear in coverage as 0% instead
// of not appearing at all. See the script for the full reasoning.
//
// ignore_for_file: unused_import

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:motto/app.dart';
import 'package:motto/config/app_crash_listener.dart';
import 'package:motto/config/env.dart';
import 'package:motto/config/injectable.dart';
import 'package:motto/features/welcome/presentation/welcome_page.dart';
import 'package:motto/main.dart';
import 'package:motto/route/app_router.dart';
import 'package:motto/theme/motto_palette.dart';
import 'package:motto/theme/motto_theme.dart';

void main() {
  test('imports every library, so untested files count as 0%', () {
    final imported = RegExp("^import 'package:motto/(.+)';", multiLine: true)
        .allMatches(File('test/coverage_helper_test.dart').readAsStringSync())
        .map((match) => 'lib/${match.group(1)}')
        .toSet();

    final onDisk = Directory('lib')
        .listSync(recursive: true)
        .whereType<File>()
        .map((file) => file.path)
        .where((path) => path.endsWith('.dart'))
        .where((path) => !path.startsWith('lib/generated/'))
        .where(
          (path) => !RegExp(r'\.(g|gr|freezed|config)\.dart$').hasMatch(path),
        )
        .toSet();

    expect(
      onDisk.difference(imported),
      isEmpty,
      reason:
          'these libraries are missing from the coverage helper — run '
          '`melos run coverage:helper`',
    );
  });
}
