#!/usr/bin/env bash
# Rebuilds the committed contracts and the Dart clients generated from them.
#
# One command on purpose: the contract and the client that consumes it are
# supposed to move together, and remembering two steps is how they stop doing
# that. CI runs this and then checks git is clean, so a resource changed without
# regenerating fails the pull request rather than the app.
set -euo pipefail

GENERATOR_VERSION=7.25.0
SERVICES=(auth motto)

root=$(cd "$(dirname "$0")/.." && pwd)
cache="${HOME}/.cache/openapi-generator"
jar="${cache}/openapi-generator-cli-${GENERATOR_VERSION}.jar"

echo "==> contracts"
"${root}/services/mvnw" -f "${root}/services/pom.xml" -B -q install -DskipTests

if [ ! -f "$jar" ]; then
  echo "==> openapi-generator ${GENERATOR_VERSION}"
  mkdir -p "$cache"
  curl -fsSL -o "$jar" \
    "https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/${GENERATOR_VERSION}/openapi-generator-cli-${GENERATOR_VERSION}.jar"
fi

for service in "${SERVICES[@]}"; do
  package="api_client_${service}"
  out="${root}/packages/${package}"

  echo "==> ${package}"
  # Removed rather than regenerated over: a deleted endpoint has to disappear
  # from the client, and generating in place would leave it behind.
  rm -rf "$out"

  java -jar "$jar" generate \
    --input-spec "${root}/contracts/${service}.v1.json" \
    --generator-name dart \
    --output "$out" \
    --additional-properties="pubName=${package},pubVersion=1.0.0" \
    > /dev/null

  # Things the generator ships that a package inside this repo has no use for.
  rm -rf "${out}/.travis.yml" "${out}/git_push.sh" "${out}/doc" \
         "${out}/.openapi-generator-ignore" "${out}/.gitignore"

  # The generated tests are empty bodies with a TODO in them. Keeping them would
  # put this package under the coverage floor that every package with a test
  # directory has to clear, and it would be measuring the generator rather than
  # anything we wrote. What actually verifies this package is that regenerating
  # it produces no diff, which CI checks.
  rm -rf "${out}/test"

  python3 - "$out" "$package" "$service" <<'PY'
import pathlib, sys

out, package, service = pathlib.Path(sys.argv[1]), sys.argv[2], sys.argv[3]

# The generated pubspec cannot know it is landing in a pub workspace, and its
# test pin is narrow enough to break resolution for everyone else.
(out / "pubspec.yaml").write_text(f"""# GENERATED by scripts/generate_api_clients.sh — do not edit.
# Regenerate instead: the contract is the source, this package is an artefact.

name: {package}
description: Generated client for the {service} service, from contracts/{service}.v1.json.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.12.0

resolution: workspace

dependencies:
  collection: ^1.19.0
  http: ^1.2.0
  intl: any
  meta: ^1.15.0
""")

# An empty analysis_options means the workspace lints do not apply here, which
# is the intent — generated code is not written to this repo's taste and there
# is no point failing a build over it. Saying so beats an empty file.
(out / "analysis_options.yaml").write_text("""# Generated code. The workspace lint set is deliberately not applied: nobody
# edits this package, so a style rule here would only ever be noise.
analyzer:
  errors:
    todo: ignore
""")
PY

  echo "    formatting"
  (cd "$out" && dart format . > /dev/null)
done

echo
echo "done. If git is dirty, the contract or the client moved — commit both."
