#!/usr/bin/env python3
"""Generates the repeatable migration that seeds the task table.

The text lives in content/tasks.yaml — one source, reviewed like every other
piece of copy. The rows live in the database, because which task a day gets is
a decision somebody will want to change without a deploy.

The seed inserts what is missing and **replaces text that is still a
placeholder**. Anything edited by hand in the database is left alone: the
moment somebody clears `placeholder` on a row, that row is theirs and no deploy
overwrites it again.

Forty-two tasks are written; each is given to all eight archetypes and marked
`placeholder`, so the writing job — one per archetype, 336 in total — is a
query rather than a memory:

    select day, archetype_id, ordinal from tasks where placeholder;

Run it after editing content/tasks.yaml, and commit the result.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
TASKS = ROOT / "content/tasks.yaml"
ARCHETYPES = ROOT / "content/archetypes.yaml"
OUTPUT = ROOT / "services/motto/src/main/resources/db/migration/R__seed_tasks.sql"

LANGUAGE = "tr"


def quote(text: str) -> str:
    return "'" + text.replace("'", "''").strip() + "'"


def main() -> int:
    tasks = yaml.safe_load(TASKS.read_text(encoding="utf-8"))["tasks"]
    archetypes = [
        item["id"]
        for item in yaml.safe_load(ARCHETYPES.read_text(encoding="utf-8"))["archetypes"]
    ]

    rows = []
    for entry in tasks:
        for ordinal, task in enumerate(entry[LANGUAGE], start=1):
            for archetype in archetypes:
                rows.append(
                    "    ({day}, {archetype}, {ordinal}, {title}, {detail}, true)".format(
                        day=entry["day"],
                        archetype=quote(archetype),
                        ordinal=ordinal,
                        title=quote(task["title"]),
                        detail=quote(task["detail"]),
                    )
                )

    body = ",\n".join(rows)
    OUTPUT.write_text(
        f"""-- Generated by scripts/seed_tasks.py from content/tasks.yaml.
-- Do not edit: run the script and commit what it writes.
--
-- Repeatable. Missing rows are inserted; rows still marked `placeholder` are
-- replaced with whatever the file now says. A row somebody has edited by hand
-- — `placeholder` cleared — is never touched again.
INSERT INTO tasks (day, archetype_id, ordinal, title, detail, placeholder)
VALUES
{body}
ON CONFLICT (day, archetype_id, ordinal) DO UPDATE
SET title = EXCLUDED.title,
    detail = EXCLUDED.detail,
    placeholder = EXCLUDED.placeholder
WHERE tasks.placeholder;
""",
        encoding="utf-8",
    )

    print(f"{OUTPUT.relative_to(ROOT)} — {len(rows)} rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
