#!/usr/bin/env python3
"""Generates the repeatable migration that seeds the deep report pieces.

Only the parts that are the same for every reader are written in
content/report.yaml — the four section skeletons and the limitations. The
seventy-two personal parts are generated as placeholders so the writing job is
a query rather than a memory:

    select kind, archetype_id, dimension, band, section
    from report_pieces where placeholder;

Repeatable and insert-if-absent, like the task seed: an edit made in the
database survives the next deploy.

Run it after editing content/report.yaml, and commit the result.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
REPORT = ROOT / "content/report.yaml"
ARCHETYPES = ROOT / "content/archetypes.yaml"
OUTPUT = ROOT / "services/motto/src/main/resources/db/migration/R__seed_report.sql"

DIMENSIONS = [
    "OPENNESS",
    "CONSCIENTIOUSNESS",
    "EXTRAVERSION",
    "AGREEABLENESS",
    "NEUROTICISM",
]
BANDS = ["low", "mid", "high"]
SECTIONS = [1, 2, 3, 4]


def quote(value) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, int):
        return str(value)
    return "'" + str(value).replace("'", "''").strip() + "'"


def row(kind, text, *, archetype=None, dimension=None, band=None, section=None,
        placeholder=False) -> str:
    return "    ({}, {}, {}, {}, {}, {}, {})".format(
        quote(kind),
        quote(archetype),
        quote(dimension),
        quote(band),
        quote(section),
        quote(text),
        "true" if placeholder else "false",
    )


def main() -> int:
    report = yaml.safe_load(REPORT.read_text(encoding="utf-8"))
    archetypes = [
        item["id"]
        for item in yaml.safe_load(ARCHETYPES.read_text(encoding="utf-8"))["archetypes"]
    ]

    rows = [row("limitation", report["limitation"]["tr"])]
    rows += [
        row("skeleton", entry["tr"], section=entry["section"])
        for entry in report["sections"]
    ]

    # 15: five dimensions, three bands each.
    for dimension in DIMENSIONS:
        for band in BANDS:
            rows.append(
                row(
                    "dimension",
                    f"[{dimension.lower()} · {band}] Bu boyuttaki eğilimin metni "
                    "henüz yazılmadı.",
                    dimension=dimension,
                    band=band,
                    placeholder=True,
                )
            )

    # 8 portraits, 32 fragments, 8 comparisons.
    for archetype in archetypes:
        rows.append(
            row(
                "portrait",
                f"[{archetype}] Arketip portresi henüz yazılmadı.",
                archetype=archetype,
                placeholder=True,
            )
        )
        rows.append(
            row(
                "comparison",
                f"[{archetype}] Yakın arketiple karşılaştırma henüz yazılmadı.",
                archetype=archetype,
                placeholder=True,
            )
        )
        for section in SECTIONS:
            rows.append(
                row(
                    "fragment",
                    f"[{archetype} · {section}] Bölüm fragmanı henüz yazılmadı.",
                    archetype=archetype,
                    section=section,
                    placeholder=True,
                )
            )

    body = ",\n".join(rows)
    OUTPUT.write_text(
        f"""-- Generated by scripts/seed_report.py from content/report.yaml.
-- Do not edit: run the script and commit what it writes.
--
-- Repeatable and insert-if-absent, so an edit made in the database survives
-- the next deploy.
INSERT INTO report_pieces (kind, archetype_id, dimension, band, section, text, placeholder)
SELECT * FROM (VALUES
{body}
) AS incoming (kind, archetype_id, dimension, band, section, text, placeholder)
WHERE NOT EXISTS (
    SELECT 1 FROM report_pieces existing
    WHERE existing.kind = incoming.kind
      AND existing.archetype_id IS NOT DISTINCT FROM incoming.archetype_id
      AND existing.dimension IS NOT DISTINCT FROM incoming.dimension
      AND existing.band IS NOT DISTINCT FROM incoming.band
      AND existing.section IS NOT DISTINCT FROM incoming.section
);
""",
        encoding="utf-8",
    )

    written = sum(1 for r in rows if "true)" not in r)
    print(
        f"{OUTPUT.relative_to(ROOT)} — {len(rows)} pieces, "
        f"{written} written, {len(rows) - written} placeholders"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
