#!/usr/bin/env bash
#
# Regenerates test/coverage_helper_test.dart.
#
# `flutter test --coverage` only instruments libraries the tests actually
# import. A file no test touches is therefore *absent* from lcov.info rather
# than reported as 0%, which quietly inflates the percentage. Importing every
# library from one file forces them all into the report.
#
# Run via `melos run coverage:helper`.

set -euo pipefail
cd "$(dirname "$0")/.."

out=test/coverage_helper_test.dart

sources() {
  find lib -name '*.dart' \
    ! -path 'lib/generated/*' \
    ! -name '*.g.dart' \
    ! -name '*.gr.dart' \
    ! -name '*.freezed.dart' \
    ! -name '*.config.dart' | sort
}

{
  echo "// GENERATED by tool/coverage_helper.sh — do not edit by hand."
  echo "//"
  echo "// Exists so that files without tests appear in coverage as 0% instead"
  echo "// of not appearing at all. See the script for the full reasoning."
  echo "//"
  echo "// ignore_for_file: unused_import"
  echo
  echo "import 'dart:io';"
  echo
  echo "import 'package:flutter_test/flutter_test.dart';"
  sources | sed "s|^lib/|import 'package:wallet/|; s|\$|';|"
  echo
  cat <<'DART'
void main() {
  test('imports every library, so untested files count as 0%', () {
    final imported =
        RegExp("^import 'package:wallet/(.+)';", multiLine: true)
            .allMatches(File('test/coverage_helper_test.dart').readAsStringSync())
            .map((match) => 'lib/${match.group(1)}')
            .toSet();

    final onDisk = Directory('lib')
        .listSync(recursive: true)
        .whereType<File>()
        .map((file) => file.path)
        .where((path) => path.endsWith('.dart'))
        .where((path) => !path.startsWith('lib/generated/'))
        .where(
          (path) => !RegExp(r'\.(g|gr|freezed|config)\.dart$').hasMatch(path),
        )
        .toSet();

    expect(
      onDisk.difference(imported),
      isEmpty,
      reason: 'these libraries are missing from the coverage helper — run '
          '`melos run coverage:helper`',
    );
  });
}
DART
} > "$out"

dart format "$out" > /dev/null
echo "wrote $out ($(sources | wc -l | tr -d ' ') libraries)"
